### ISSUE TITLE
Build problem Turtle

### ISSUE THREAD

**Issue by labmoonwalk** [expo/turtle#104]
Hi guys.

Im trying to generate a build (with turtle) of one of my projects but its facing the following problem, as you can see on attached file.

Can anyone help me?

Thanks,

![WhatsApp Image 2019-06-26 at 10 55 31](https://user-images.githubusercontent.com/52249337/60189339-1ff73b00-9807-11e9-9775-3db4af9333de.jpeg)

**Comment by dsokal** [comment]
Hello @labmoonwalk,

could you please provide more logs? The error you posted is too generic to help you, sorry!

**Comment by labmoonwalk** [comment]
Hello @dsokal
Sorry about delay.

Bellow you can see the log.
Thanks,

![Captura de Tela 2019-06-27 às 19 39 21](https://user-images.githubusercontent.com/52249337/60347115-ff5bec00-9992-11e9-8099-c4d754d3a97f.png)

**Comment by dsokal** [comment]
I think the error is self-explaining.

**Comment by labmoonwalk** [comment]
Sorry for the last screen. :/
Now im facing the following error:

15726 error path /Users/alexmoret/.turtle/workingdir/android/sdk32/tools-public/node_modules/.bin/bunyan
15727 error code EEXIST
15728 error Refusing to delete /Users/alexmoret/.turtle/workingdir/android/sdk32/tools-public/node_modules/.bin/bunyan: is outside /Users/alexmoret/.turtle/workingdir/android/sdk32/tools-public/node_modules/@expo/bunyan and not a link
15729 error File exists: /Users/alexmoret/.turtle/workingdir/android/sdk32/tools-public/node_modules/.bin/bunyan
15730 error Move it away, and try again.
15731 verbose exit [ 1, true ]

Can you help me?

**Comment by dsokal** [comment]
Have you by any chance installed the `turtle-cli` package with sudo? It looks like you did and now you're running `turtle` without sudo.

**Comment by labmoonwalk** [comment]
Hi, @dsokal.
I already deleted the package and installed again, but I still facing the following error:

![Captura de Tela 2019-07-12 às 11 45 45](https://user-images.githubusercontent.com/52249337/61136805-a152fc80-a49a-11e9-9179-7a32851a4014.png)

**Comment by dsokal** [comment]
@labmoonwalk please upgrade turtle-cli to the latest version - 0.8.9 and try again

**Comment by labmoonwalk** [comment]
@dsokal 

Although I have updated the turtle and logged in the following message appears

![Captura de Tela 2019-07-15 às 09 51 44](https://user-images.githubusercontent.com/52249337/61217557-51687580-a6e6-11e9-84f6-e1e4f030da49.png)

**Comment by dsokal** [comment]
I recommend you to change the password for your Expo user :)
Also, running turtle-cli with sudo isn't supported, sorry.

**Comment by labmoonwalk** [comment]
I will change the password. :)
I could not update turtle without sudo.
How can I give me access without sudo?

**Comment by dsokal** [comment]
Try installing `nvm` - https://github.com/nvm-sh/nvm Thanks to that tool you will be able to install node packages globally (such as `turtle-cli`) without using `sudo`.

**Comment by labmoonwalk** [comment]
Hi @dsokal 
Im using the latest version of npm and node. I have tried to run npm rebuild but it doesn't work.
Can you help me?

![Captura de Tela 2019-07-24 às 23 06 57](https://user-images.githubusercontent.com/52249337/61840525-cd418b00-ae67-11e9-91e6-279aa56f1ecb.png)

**Comment by dsokal** [comment]
Have you installed `nvm` as I adviced in my previous comment? Try switching to node 8.

**Comment by labmoonwalk** [comment]
@dsokal The error has changed.
Do you think still need to install nvm or just switching to node 8?

**Comment by labmoonwalk** [comment]
Wheh - found the problem! The issue is the turtle-cli project. They import an old version of the @google-cloud/logging-bunyan library, which takes the dependency on grpc. The problem is this:
https://github.com/expo/turtle/blob/master/package.json#L101

They need to upgrade to the latest version (> 1.0) of @google-cloud/logging-bunyan, ship a new release of their module, and then you should be set.
