### ISSUE TITLE
Turtle error

### ISSUE THREAD

**Issue by labmoonwalk** [expo/turtle#106]
Hi folks.

Im facing the following problem when trying to generate an app via turtle.

Can anyone help me?

![turtle](https://user-images.githubusercontent.com/52249337/60462761-938eb300-9c20-11e9-8057-e0da8907f329.jpeg)

**Comment by dsokal** [comment]
Hi,
could you please share the whole log output? You can get the logs file by running turtle-cli like this: `turtle build:PLATFORM ... | tee logs.txt`. Once the turtle exits you will have the logs in the `logs.txt` file.

Is it by any chance related to https://github.com/expo/turtle/issues/104 ? :)

**Comment by labmoonwalk** [comment]
Hello,
This command is not recognizeed by turtle, as you can see:

![Captura de Tela 2019-07-02 às 09 03 27](https://user-images.githubusercontent.com/52249337/60511434-4fdf8c00-9ca8-11e9-97af-3e53de7cc74d.png)

**Comment by labmoonwalk** [comment]
Hi,
Attached the logs.

[logs.txt](https://github.com/expo/turtle/files/3350001/logs.txt)

Thanks,

**Comment by dsokal** [comment]
It's the same issue as #104 - https://github.com/expo/turtle/issues/104#issuecomment-507581351
I'm closing this one.
