### ISSUE TITLE
iOS Build error while build and signing phase 

### ISSUE THREAD

**Issue by rompjin** [expo/turtle#111]
Hi!

I don't know what's wrong with building errors.
Please, what's the problem?

  **Expo CLI 2.21.2 environment info:**
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.15.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.2 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.19 => 16.8.22 
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.21.2

**Here are error logs**

Jul 8 10:17:43 turtle[921] INFO:  +-------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:43 turtle[921] INFO:  INFO [2019-07-08 10:17:43.81]: $ /usr/bin/xcrun /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/gym_config20190708-1052-19kfhik.plist' -archivePath /private/tmp/turtle/84373e67-190f-4a10-bc91-fddf9e1069dc/archive.xcarchive -exportPath '/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/gym_output20190708-1052-1l5qutm' OTHER_CODE_SIGN_FLAGS="--keychain /private/tmp/xdl/f5f3cd30-a11d-11e9-92a2-911953e87c46.keychain" 
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:43 turtle[921] INFO:  INFO [2019-07-08 10:17:43.83]: ▸ rbenv detected, removing env variables
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:43 turtle[921] INFO:  INFO [2019-07-08 10:17:43.85]: ▸ rbenv: shell integration not enabled. Run `rbenv init' for instructions.
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:43 turtle[921] INFO:  INFO [2019-07-08 10:17:43.85]: ▸ + xcodebuild -exportArchive -exportOptionsPlist /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/gym_config20190708-1052-19kfhik.plist -archivePath /private/tmp/turtle/84373e67-190f-4a10-bc91-fddf9e1069dc/archive.xcarchive -exportPath /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/gym_output20190708-1052-1l5qutm 'OTHER_CODE_SIGN_FLAGS=--keychain /private/tmp/xdl/f5f3cd30-a11d-11e9-92a2-911953e87c46.keychain'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:44 turtle[921] INFO:  INFO [2019-07-08 10:17:44.36]: ▸ 2019-07-08 10:17:44.359 xcodebuild[1088:32714] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/ExpoKitApp_2019-07-08_10-17-44.359.xcdistributionlogs'.
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:46 turtle[921] INFO:  INFO [2019-07-08 10:17:46.83]: ▸ error: exportArchive: No "iOS App Store" profiles for team 'B7NTR7J7VN' matching 'io.x7chat.viiluck AppStore' are installed.
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:46 turtle[921] INFO:  INFO [2019-07-08 10:17:46.83]: ▸ Error Domain=IDEProfileLocatorErrorDomain Code=4 "No "iOS App Store" profiles for team 'B7NTR7J7VN' matching 'io.x7chat.viiluck AppStore' are installed." UserInfo={NSLocalizedDescription=No "iOS App Store" profiles for team 'B7NTR7J7VN' matching 'io.x7chat.viiluck AppStore' are installed., NSLocalizedRecoverySuggestion=Install a profile (by dragging and dropping it onto Xcode's dock item) or specify a different profile in your Export Options property list.}
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:46 turtle[921] INFO:  INFO [2019-07-08 10:17:46.83]: ▸ ** EXPORT FAILED **
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  rbenv detected, removing env variables
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  rbenv: shell integration not enabled. Run `rbenv init' for instructions.
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  + xcodebuild -exportArchive -exportOptionsPlist /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/gym_config20190708-1052-19kfhik.plist -archivePath /private/tmp/turtle/84373e67-190f-4a10-bc91-fddf9e1069dc/archive.xcarchive -exportPath /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/gym_output20190708-1052-1l5qutm 'OTHER_CODE_SIGN_FLAGS=--keychain /private/tmp/xdl/f5f3cd30-a11d-11e9-92a2-911953e87c46.keychain'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  2019-07-08 10:17:44.359 xcodebuild[1088:32714] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/ExpoKitApp_2019-07-08_10-17-44.359.xcdistributionlogs'.
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  error: exportArchive: No "iOS App Store" profiles for team 'B7NTR7J7VN' matching 'io.x7chat.viiluck AppStore' are installed.
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  Error Domain=IDEProfileLocatorErrorDomain Code=4 "No "iOS App Store" profiles for team 'B7NTR7J7VN' matching 'io.x7chat.viiluck AppStore' are installed." UserInfo={NSLocalizedDescription=No "iOS App Store" profiles for team 'B7NTR7J7VN' matching 'io.x7chat.viiluck AppStore' are installed., NSLocalizedRecoverySuggestion=Install a profile (by dragging and dropping it onto Xcode's dock item) or specify a different profile in your Export Options property list.}
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  ** EXPORT FAILED **
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  ERROR [2019-07-08 10:17:47.07]: Exit status: 70
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  +---------------+-------------------------+
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  |            Build environment            |
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  +---------------+-------------------------+
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  | xcode_path    | /Applications/Xcode.app |
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  | gym_version   | 2.125.2                 |
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  | export_method | app-store               |
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  | sdk           | iPhoneOS12.2.sdk        |
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  +---------------+-------------------------+
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  INFO [2019-07-08 10:17:47.10]: 
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  ERROR [2019-07-08 10:17:47.10]: Looks like fastlane ran into a build/archive error with your project
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  ERROR [2019-07-08 10:17:47.10]: It's hard to tell what's causing the error, so we wrote some guides on how
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  ERROR [2019-07-08 10:17:47.10]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  ERROR [2019-07-08 10:17:47.10]: Before submitting an issue on GitHub, please follow the guide above and make
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  ERROR [2019-07-08 10:17:47.10]: sure your project is set up correctly.
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  ERROR [2019-07-08 10:17:47.10]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  ERROR [2019-07-08 10:17:47.10]: the full commands printed out in yellow in the above log.
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  ERROR [2019-07-08 10:17:47.10]: Make sure to inspect the output above, as usually you'll find more error information there
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  INFO [2019-07-08 10:17:47.10]: 
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"
Jul 8 10:17:47 turtle[921] INFO:  /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane_core/lib/fastlane_core/ui/interface.rb:163:in `build_failure!': [!] Error packaging up the application (FastlaneCore::Interface::FastlaneBuildFailure)
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/gym/lib/gym/error_handler.rb:112:in `handle_package_error'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/gym/lib/gym/runner.rb:138:in `block in package_app'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane_core/lib/fastlane_core/command_executor.rb:89:in `execute'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/gym/lib/gym/runner.rb:134:in `package_app'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/gym/lib/gym/runner.rb:27:in `run'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/gym/lib/gym/manager.rb:19:in `work'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/gym/lib/gym/commands_generator.rb:44:in `block (2 levels) in run'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/gym/lib/gym/commands_generator.rb:75:in `run'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/gym/lib/gym/commands_generator.rb:15:in `start'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/bin/fastlane:23:in `<top (required)>'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/bin/fastlane:23:in `load'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/bin/fastlane:23:in `<main>'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane_core/lib/fastlane_core/ui/interface.rb:163:in `build_failure!': Error packaging up the application (FastlaneCore::Interface::FastlaneBuildFailure)
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/gym/lib/gym/error_handler.rb:112:in `handle_package_error'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/gym/lib/gym/runner.rb:138:in `block in package_app'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane_core/lib/fastlane_core/command_executor.rb:89:in `execute'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/gym/lib/gym/runner.rb:134:in `package_app'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/gym/lib/gym/runner.rb:27:in `run'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/gym/lib/gym/manager.rb:19:in `work'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/gym/lib/gym/commands_generator.rb:44:in `block (2 levels) in run'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/gym/lib/gym/commands_generator.rb:75:in `run'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/gym/lib/gym/commands_generator.rb:15:in `start'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.125.2/bin/fastlane:23:in `<top (required)>'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/bin/fastlane:23:in `load'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  	from /Users/numbers/.rbenv/versions/2.6.3/bin/fastlane:23:in `<main>'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Jul 8 10:17:47 turtle[921] INFO:  removed provisioning profile from the home directory
  platform: "ios"
  buildPhase: "building and signing IPA"
Jul 8 10:17:47 turtle[921] ERROR: Error: fastlane exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/numbers/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:281:20)
    at ChildProcess.emit (events.js:193:13)
    at ChildProcess.EventEmitter.emit (domain.js:481:20)
    at maybeClose (internal/child_process.js:999:16)
    at Socket.stream.socket.on (internal/child_process.js:403:11)
    at Socket.emit (events.js:193:13)
    at Socket.EventEmitter.emit (domain.js:481:20)
    at Pipe._handle.close (net.js:614:12)
    ...
    at spawnAsync (/Users/numbers/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnAsyncThrowError (/@expo/xdl@55.0.7/src/detach/ExponentTools.js:126:21)
    at runFastlane (/@expo/xdl@55.0.7/src/detach/IosCodeSigning.js:356:9)
    at Object.buildIPA (/@expo/xdl@55.0.7/src/detach/IosCodeSigning.js:172:11)
    at Object.build (/@expo/xdl@55.0.7/src/detach/IosIPABuilder.js:67:28)
  platform: "ios"
Jul 8 10:17:47 turtle[921] INFO:  delete keychain...
  platform: "ios"
  buildPhase: "deleting keychain"
Jul 8 10:17:47 turtle[921] INFO:  deleting keychain...
  platform: "ios"
  buildPhase: "deleting keychain"
Jul 8 10:17:48 turtle[921] INFO:  done deleting keychain
  platform: "ios"
  buildPhase: "deleting keychain"
Jul 8 10:17:49 turtle[921] ERROR: Failed to build standalone app
  err: Error: fastlane exited with non-zero code: 1
      at ChildProcess.completionListener (/Users/numbers/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:281:20)
      at ChildProcess.emit (events.js:193:13)
      at ChildProcess.EventEmitter.emit (domain.js:481:20)
      at maybeClose (internal/child_process.js:999:16)
      at Socket.stream.socket.on (internal/child_process.js:403:11)
      at Socket.emit (events.js:193:13)
      at Socket.EventEmitter.emit (domain.js:481:20)
      at Pipe._handle.close (net.js:614:12)
      ...
      at spawnAsync (/Users/numbers/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at spawnAsyncThrowError (/@expo/xdl@55.0.7/src/detach/ExponentTools.js:126:21)
      at runFastlane (/@expo/xdl@55.0.7/src/detach/IosCodeSigning.js:356:9)
      at Object.buildIPA (/@expo/xdl@55.0.7/src/detach/IosCodeSigning.js:172:11)
      at Object.build (/@expo/xdl@55.0.7/src/detach/IosIPABuilder.js:67:28)
  platform: "ios"

Thanks!!!

**Comment by rompjin** [comment]
Additionally, Everything is fine when build it in Expo.
I don't think there's anything wrong with the signings.

Thanks

**Comment by dsokal** [comment]
Hello,
have you read the logs?

`No "iOS App Store" profiles for team 'B7NTR7J7VN' matching 'io.x7chat.viiluck AppStore' are installed.`

I think you are trying to use the wrong provisioning profile.

**Comment by rompjin** [comment]
@dsokal  Thanks for your reply.
Well, I have never thought it cause the wrong provisioning profile because I just got it from expo like...
$ expo fetch:ios:certs

Did I miss anything?

**Comment by dsokal** [comment]
What's the full `turtle-cli` command you were trying to run?

**Comment by rompjin** [comment]
**$ sudo EXPO_IOS_DIST_P12_PASSWORD=SJ94hZexo9KzitA7dLwSVQ== turtle bi --public-url https://7chat.gamepia.net/app/update_ent/ios-index.json --team-id B7NTR7J7VN --dist-p12-path ./7Chat_dist.p12 --provisioning-profile-path ./7Chat.mobileprovision**

**Comment by dsokal** [comment]
Try without `sudo`

**Comment by rompjin** [comment]
I got errors =>

Jul 8 17:26:55 turtle[5149] ERROR: Error: EACCES: permission denied, mkdir '/private/tmp/turtle/9bb593da-05e6-4a66-adaa-6a9055b73024'
  platform: "ios"
Jul 8 17:26:55 turtle[5149] ERROR: Failed to build standalone app
  err: Error: EACCES: permission denied, mkdir '/private/tmp/turtle/9bb593da-05e6-4a66-adaa-6a9055b73024'
  platform: "ios"

**Comment by dsokal** [comment]
That's strange, does your user have limited permissions? Basically, this error means that you don't have permissions to create a new directory in `/tmp` which is super weird. I think this is a problem with your system.

**Comment by raghu1286** [comment]
@dsokal - I'm getting the same error when running the command with ```sudo```, 
```
Error Domain=IDEProfileLocatorErrorDomain Code=4 "No "iOS Ad Hoc" profiles for team '<obfuscated>' matching '032a8cc2-c70e-4276-a6ae-035fa9bc0ec1' are installed." UserInfo={NSLocalizedDescription=No "iOS Ad Hoc" profiles for team '<obfuscated>' matching '032a8cc2-c70e-4276-a6ae-035fa9bc0ec1' are installed., NSLocalizedRecoverySuggestion=Install a profile (by dragging and dropping it onto Xcode's dock item) or specify a different profile in your Export Options property list.}
  platform: "ios"

but without sudo fastlane fails with error,
``` ERROR: unable to create keychain ```.

The same certificate & provisioning profile are working with ``` expo build:ios ```

Any suggestions?

Thanks!

**Comment by raghu1286** [comment]
@rompjin - Were you able to fix the errors & get this working? I'm stuck in exactly the same situation as you.

**Comment by rompjin** [comment]
@raghu1286  Unfortunately, I've tried some things, but they don't work. Same problem with other fellow Mac. I don't have any clue.

**Comment by rompjin** [comment]
@raghu1286 But I don't think your case is the same as mine.

**Comment by raghu1286** [comment]
@rompjin - Thanks for your reply. I got it working on my Mac, what I figured out was, when the "turtle" command is run with "sudo" the folders in /private/tmp get created with root user, so when you remove "sudo" next time the permissions error is thrown.. To get it working I deleted ``` /private/tmp/xdl``` & ```/private/tmp/turtle``` that fixed the permission errors & the certificate errors.. What I understood is, the turtle command should never be run with sudo..

**Comment by rompjin** [comment]
@raghu1286  Thanks for your reply. 
When I command 'turtle' with 'sudo', there was no problem with the permission I thnk. All the temporary files and directories were removed without any problems.
Just log out
**No "iOS App Store" profiles for team 'B7NTR7J7VN' matching 'io.x7chat.vieluck AppStore' are installed.** 
But I don't know what this has to do with the permission.

**Comment by dsokal** [comment]
@rompjin Please let me know whether you're still experiencing the issue and if not - how you fixed that.

**Comment by dsokal** [comment]
Hi, 
I'm closing the issue because of inactivity. Please let me know if the problem still exists.
