### ISSUE TITLE
Cannot read property 'getCurrentUserAsync' of undefined

### ISSUE THREAD

**Issue by borgogelli** [expo/turtle#114]
I use turtle 0.8.8 and when I run the command

`$ turtle build:android --keystore-path ${ANDROID_APK_PATH}/${KEYSTORE_FILE_NAME} --keystore-alias ${KEYSTORE_ALIAS} --type apk --output ${APK_FILE}`

I get the error:

```
turtle[4008] ERROR: Failed to build standalone app
  err: TypeError: Cannot read property 'getCurrentUserAsync' of undefined
      at Object.ensureUserLoggedIn (/usr/local/lib/node_modules/turtle-cli/src/bin/utils/user.ts:11:41)
      at /usr/local/lib/node_modules/turtle-cli/src/bin/utils/builder.ts:47:27
      at Command.action (/usr/local/lib/node_modules/turtle-cli/src/bin/index.ts:23:18)
      at <anonymous>
  platform: "android"

```

**Comment by borgogelli** [comment]
Rolling back to the 0.8.3 versione, solves the problem

**Comment by derekstavis** [comment]
I'm having the same issue with `turtle build:ios`. Confirmed that reverting to 0.8.3 solves the issue.

**Comment by dsokal** [comment]
Sorry guys for the inconvenience - I just release a new version - 0.8.9 - which fixes the issue.

**Comment by borgogelli** [comment]
@dsokal Thank you
