### ISSUE TITLE
`build:ios` fails with Xcode 10.3

### ISSUE THREAD

**Issue by jhogervorst** [expo/turtle#117]
### New Issue Checklist
- [x] Updated turtle-cli to the latest version (`yarn global add turtle-cli` or `npm install --global turtle-cli`).
- [x] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [x] I read [docs.expo.io](https://docs.expo.io) (Managed Workflow > Distributing Your App).
- [x] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).
- [x] **I enclosed the complete output when running turtle, including the stack trace and command used.**

### Issue Description

After updating to Xcode 10.3, the `build:ios` command fails with an error.

After installing Xcode 10.2.1 again, and switching the Command Line Tools version in the Xcode preferences, the build command runs fine again. I did not change anything else, the only difference was the active Xcode version.

##### Command executed

```bash
npx turtle build:ios --release-channel beta --team-id [REDACTED] --dist-p12-path ios.p12 --provisioning-profile-path ios.mobileprovision --output ios.ipa ..
```

##### Complete output when running turtle, including the stack trace and command used
<details>
<pre>
$ npx turtle build:ios --release-channel beta --team-id [REDACTED] --dist-p12-path ios.p12 --provisioning-profile-path ios.mobileprovision --output ios.ipa ..
Jul 23 11:12:07 turtle[38996] INFO:  Using manifest: {"android":{"adaptiveIcon":{"backgroundImage":"./assets/images/icon-background.png","backgroundImageUrl":"https://[REDACTED].cloudfront.net/~assets/[REDACTED]","foregroundImage":"./assets/images/icon-foreground.png","foregroundImageUrl":"https://[REDACTED].cloudfront.net/~assets/[REDACTED]"},"package":"[REDACTED]","permissions":["CAMERA","READ_EXTERNAL_STORAGE","WRITE_EXTERNAL_STORAGE"],"versionCode":1},"bundledAssets":["asset_e50385879b0fb7b90c21418b57f2af5f.png","asset_9ae936e13a4796136ef04fb617791bc6.png","asset_f661153a0a71a6789230d7561af9dc9d.png","asset_9c697b5ae187828d365e3239cafbef0f.png","asset_b699d4f9f0f978d40b8afa1d88cfcd9f.png","asset_bc185e9581d6444efedace6c55e8f0bf.png","asset_daa76ab2f8e8baf51b217b0825ff890f.png","asset_e7c4ed5376f6fd6d17193d6963f1628d.png","asset_4e13b62be9b35fea4cfd62f5a3a7deb4.png","asset_3724bddf357c02572f786f4589709dd0.png","asset_ac48bd00c775d54b150f6b0d62cb5430.png","asset_3c48429e5bc9c4c6e183f11c1e230a73.png","asset_62a6eed52720f827f90b897ecc416d3a.png","asset_6ac6d217b8a50bb2757cd6cd81f7819d.png","asset_491477f86fee0e52f6d5990f32925cb3.png","asset_fe5f2db638044da7ac41ffb9b7bbfb0f.png","asset_cb4c3407976958c913906b0dba45eab2.png","asset_75bc1005e1b82f2f1eeb0f4b908bc07a.png","asset_7c04aa83177f9d16c4322ef05c02e505.png","asset_9980cd80016fefd4d61def17f05258b2.png","asset_9e6f14cbe5583e7e08173d3e34668baa.png","asset_101800f68459dea722959385797b3c52.png","asset_a6ca3860b8ea210934ab05f40bc49451.png","asset_b16939b201764f9878fba4aebeb13ffb.png","asset_11feed3ba0ce1156435e6fe235ec8afd.png","asset_332efe8eef6df13cee9993985c5850cd.png","asset_3e39b6a3720c4d13dd2b21afe50f0305.png"],"dependencies":["@expo/react-native-action-sheet","expo","i18n-js","lodash","react","react-native","react-native-calendars","react-native-image-zoom-viewer","react-native-modal-datetime-picker","react-native-percentage-circle","react-native-picker-select","react-native-root-toast","react-navigation","react-navigation-header-buttons","react-redux","redux","redux-persist","redux-persist-expo-filesystem","rn-uuid","rn-viewpager","xdate"],"description":"[REDACTED]","icon":"./assets/images/icon.png","iconUrl":"https://[REDACTED].cloudfront.net/~assets/[REDACTED]","ios":{"buildNumber":"31","bundleIdentifier":"[REDACTED]","infoPlist":{"NSCalendarsUsageDescription":"[REDACTED]","NSCameraUsageDescription":"[REDACTED]","NSPhotoLibraryAddUsageDescription":"[REDACTED]","NSPhotoLibraryUsageDescription":"[REDACTED]"}},"locales":{},"name":"[REDACTED]","orientation":"portrait","platforms":["ios","android"],"primaryColor":"#007aff","privacy":"unlisted","sdkVersion":"32.0.0","slug":"[REDACTED]","splash":{"backgroundColor":"#ffffff","image":"./assets/images/splash.png","imageUrl":"https://[REDACTED].cloudfront.net/~assets/[REDACTED]","resizeMode":"contain"},"updates":{"enabled":false},"version":"1.0","id":"[REDACTED]","revisionId":"1.0-r.Yv1pOmz4rv","publishedTime":"2019-07-23T08:29:07.286Z","commitTime":"2019-07-23T08:29:07.329Z","bundleUrl":"https://[REDACTED].cloudfront.net/[REDACTED]%2F1.0%2Fad40f57d7e7a9c350298c80d39e77887-32.0.0-ios.js","releaseChannel":"beta","hostUri":"exp.host/[REDACTED]?release-channel=beta"}
  platform: "ios"
  buildPhase: "reading manifest"
Jul 23 11:12:07 turtle[38996] INFO:  creating keychain...
  platform: "ios"
  buildPhase: "creating keychain"
Jul 23 11:12:07 turtle[38996] INFO:  creating new keychain...
  platform: "ios"
  buildPhase: "creating keychain"
Jul 23 11:12:15 turtle[38996] INFO:  Executing command: security show-keychain-info /private/tmp/xdl/f1b4e7a0-ad29-11e9-99e6-439c677c2eef.keychain
  platform: "ios"
  buildPhase: "creating keychain"
Jul 23 11:12:15 turtle[38996] INFO:  Keychain "/private/tmp/xdl/f1b4e7a0-ad29-11e9-99e6-439c677c2eef.keychain" timeout=360000s
  platform: "ios"
  buildPhase: "creating keychain"
  source: "stdout"
Jul 23 11:12:15 turtle[38996] INFO:  created new keychain
  platform: "ios"
  buildPhase: "creating keychain"
Jul 23 11:12:15 turtle[38996] INFO:  done creating keychain
  platform: "ios"
  buildPhase: "creating keychain"
Jul 23 11:12:15 turtle[38996] INFO:  importing distribution certificate into keychain...
  platform: "ios"
  buildPhase: "importing certificate into keychain"
Jul 23 11:12:15 turtle[38996] INFO:  importing certificate into keychain...
  platform: "ios"
  buildPhase: "importing certificate into keychain"
Jul 23 11:12:15 turtle[38996] INFO:  certificate has password
  platform: "ios"
  buildPhase: "importing certificate into keychain"
Jul 23 11:12:15 turtle[38996] INFO:  2 identities imported.
  platform: "ios"
  buildPhase: "importing certificate into keychain"
  source: "stdout"
Jul 23 11:12:15 turtle[38996] INFO:  imported certificate into keychain
  platform: "ios"
  buildPhase: "importing certificate into keychain"
Jul 23 11:12:15 turtle[38996] INFO:  done importing distribution certificate into keychain
  platform: "ios"
  buildPhase: "importing certificate into keychain"
Jul 23 11:12:21 turtle[38996] INFO:  ImageUtils: setting image functions to alternative sharp implementations
  platform: "ios"
  buildPhase: "icons setup"
Jul 23 11:12:21 turtle[38996] INFO:  configuring NSBundle...
  platform: "ios"
  buildPhase: "configuring NSBundle"
Jul 23 11:12:21 turtle[38996] INFO:  Using manifest: {"android":{"adaptiveIcon":{"backgroundImage":"./assets/images/icon-background.png","backgroundImageUrl":"https://[REDACTED].cloudfront.net/~assets/[REDACTED]","foregroundImage":"./assets/images/icon-foreground.png","foregroundImageUrl":"https://[REDACTED].cloudfront.net/~assets/[REDACTED]"},"package":"[REDACTED]","permissions":["CAMERA","READ_EXTERNAL_STORAGE","WRITE_EXTERNAL_STORAGE"],"versionCode":1},"bundledAssets":["asset_e50385879b0fb7b90c21418b57f2af5f.png","asset_9ae936e13a4796136ef04fb617791bc6.png","asset_f661153a0a71a6789230d7561af9dc9d.png","asset_9c697b5ae187828d365e3239cafbef0f.png","asset_b699d4f9f0f978d40b8afa1d88cfcd9f.png","asset_bc185e9581d6444efedace6c55e8f0bf.png","asset_daa76ab2f8e8baf51b217b0825ff890f.png","asset_e7c4ed5376f6fd6d17193d6963f1628d.png","asset_4e13b62be9b35fea4cfd62f5a3a7deb4.png","asset_3724bddf357c02572f786f4589709dd0.png","asset_ac48bd00c775d54b150f6b0d62cb5430.png","asset_3c48429e5bc9c4c6e183f11c1e230a73.png","asset_62a6eed52720f827f90b897ecc416d3a.png","asset_6ac6d217b8a50bb2757cd6cd81f7819d.png","asset_491477f86fee0e52f6d5990f32925cb3.png","asset_fe5f2db638044da7ac41ffb9b7bbfb0f.png","asset_cb4c3407976958c913906b0dba45eab2.png","asset_75bc1005e1b82f2f1eeb0f4b908bc07a.png","asset_7c04aa83177f9d16c4322ef05c02e505.png","asset_9980cd80016fefd4d61def17f05258b2.png","asset_9e6f14cbe5583e7e08173d3e34668baa.png","asset_101800f68459dea722959385797b3c52.png","asset_a6ca3860b8ea210934ab05f40bc49451.png","asset_b16939b201764f9878fba4aebeb13ffb.png","asset_11feed3ba0ce1156435e6fe235ec8afd.png","asset_332efe8eef6df13cee9993985c5850cd.png","asset_3e39b6a3720c4d13dd2b21afe50f0305.png"],"dependencies":["@expo/react-native-action-sheet","expo","i18n-js","lodash","react","react-native","react-native-calendars","react-native-image-zoom-viewer","react-native-modal-datetime-picker","react-native-percentage-circle","react-native-picker-select","react-native-root-toast","react-navigation","react-navigation-header-buttons","react-redux","redux","redux-persist","redux-persist-expo-filesystem","rn-uuid","rn-viewpager","xdate"],"description":"[REDACTED]","icon":"./assets/images/icon.png","iconUrl":"https://[REDACTED].cloudfront.net/~assets/[REDACTED]","ios":{"buildNumber":"31","bundleIdentifier":"[REDACTED]","infoPlist":{"NSCalendarsUsageDescription":"[REDACTED]","NSCameraUsageDescription":"[REDACTED]","NSPhotoLibraryAddUsageDescription":"[REDACTED]","NSPhotoLibraryUsageDescription":"[REDACTED]"}},"locales":{},"name":"[REDACTED]","orientation":"portrait","platforms":["ios","android"],"primaryColor":"#007aff","privacy":"unlisted","sdkVersion":"32.0.0","slug":"[REDACTED]","splash":{"backgroundColor":"#ffffff","image":"./assets/images/splash.png","imageUrl":"https://[REDACTED].cloudfront.net/~assets/[REDACTED]","resizeMode":"contain"},"updates":{"enabled":false},"version":"1.0","id":"[REDACTED]","revisionId":"1.0-r.Yv1pOmz4rv","publishedTime":"2019-07-23T08:29:07.286Z","commitTime":"2019-07-23T08:29:07.329Z","bundleUrl":"https://[REDACTED].cloudfront.net/[REDACTED]%2F1.0%2Fad40f57d7e7a9c350298c80d39e77887-32.0.0-ios.js","releaseChannel":"beta","hostUri":"exp.host/[REDACTED]?release-channel=beta"}
  platform: "ios"
  buildPhase: "reading manifest"
Jul 23 11:12:21 turtle[38996] INFO:  Modifying NSBundle configuration at /private/tmp/turtle/fa0f2c4b-943b-4ab1-a062-b3b948a3d421/archive/Release/ExpoKitApp.xcarchive/Products/Applications/ExpoKitApp.app...
  platform: "ios"
  buildPhase: "configuring NSBundle"
Jul 23 11:12:21 turtle[38996] INFO:  Using standalone config: { isShell: true,
  manifestUrl: 'https://exp.host:443/[REDACTED]',
  releaseChannel: 'beta',
  testEnvironment: 'none',
  areRemoteUpdatesEnabled: false }
  platform: "ios"
  buildPhase: "configuring NSBundle"
Jul 23 11:12:21 turtle[38996] INFO:  Configuring iOS Launch Screen...
  platform: "ios"
  buildPhase: "configuring NSBundle"
2019-07-23 11:12:24.260 ibtoold[39080:454284] [MT] IBPlatformTool: *** Failed to launch tool with description <IBCocoaTouchPlatformToolDescription: 0x7fbffa682550> System content for IBCocoaTouchFramework-ElevenAndLater <IBScaleFactorDeviceTypeDescription: 0x7fbffa9296a0> scaleFactor=2x: Failed to find or create execution context for description '<IBCocoaTouchPlatformToolDescription: 0x7fbffa682550> System content for IBCocoaTouchFramework-ElevenAndLater <IBScaleFactorDeviceTypeDescription: 0x7fbffa9296a0> scaleFactor=2x'. These intermediate objects were non-nil: (
    "IBSimDeviceTypeiPad2x (com.apple.dt.Xcode.IBSimDeviceType.iPad-2x)",
    "iOS 12.4 (12.4 - 16G73) - com.apple.CoreSimulator.SimRuntime.iOS-12-4"
): Failed to find a suitable device for the type IBSimDeviceTypeiPad2x (com.apple.dt.Xcode.IBSimDeviceType.iPad-2x) with runtime iOS 12.4 (12.4 - 16G73) - com.apple.CoreSimulator.SimRuntime.iOS-12-4 (Failure reason: Failed to create new simulator device that matches IBSimDeviceTypeiPad2x (com.apple.dt.Xcode.IBSimDeviceType.iPad-2x) for runtime iOS 12.4 (12.4 - 16G73) - com.apple.CoreSimulator.SimRuntime.iOS-12-4 (Invalid runtime: com.apple.CoreSimulator.SimRuntime.iOS-12-4)): Invalid runtime: com.apple.CoreSimulator.SimRuntime.iOS-12-4
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>com.apple.ibtool.errors</key>
        <array>
                <dict>
                        <key>description</key>
                        <string>Failed to find or create execution context for description '&lt;IBCocoaTouchPlatformToolDescription: 0x7fbffa682550&gt; System content for IBCocoaTouchFramework-ElevenAndLater &lt;IBScaleFactorDeviceTypeDescription: 0x7fbffa9296a0&gt; scaleFactor=2x'. These intermediate objects were non-nil: (
    "IBSimDeviceTypeiPad2x (com.apple.dt.Xcode.IBSimDeviceType.iPad-2x)",
    "iOS 12.4 (12.4 - 16G73) - com.apple.CoreSimulator.SimRuntime.iOS-12-4"
)</string>
                        <key>underlying-errors</key>
                        <array>
                                <dict>
                                        <key>description</key>
                                        <string>Failed to find a suitable device for the type IBSimDeviceTypeiPad2x (com.apple.dt.Xcode.IBSimDeviceType.iPad-2x) with runtime iOS 12.4 (12.4 - 16G73) - com.apple.CoreSimulator.SimRuntime.iOS-12-4</string>
                                        <key>failure-reason</key>
                                        <string>Failed to create new simulator device that matches IBSimDeviceTypeiPad2x (com.apple.dt.Xcode.IBSimDeviceType.iPad-2x) for runtime iOS 12.4 (12.4 - 16G73) - com.apple.CoreSimulator.SimRuntime.iOS-12-4 (Invalid runtime: com.apple.CoreSimulator.SimRuntime.iOS-12-4)</string>
                                        <key>underlying-errors</key>
                                        <array>
                                                <dict>
                                                        <key>description</key>
                                                        <string>Invalid runtime: com.apple.CoreSimulator.SimRuntime.iOS-12-4</string>
                                                </dict>
                                        </array>
                                </dict>
                        </array>
                </dict>
        </array>
</dict>
</plist>
{ Error: ibtool exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/Jonathan/Projecten/[REDACTED]/[REDACTED]/[REDACTED]/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
    ...
    at spawnAsync (/Users/Jonathan/Projecten/[REDACTED]/[REDACTED]/[REDACTED]/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnAsyncThrowError (/@expo/xdl@56.0.1-rc.1/src/detach/ExponentTools.ts:131:19)
    at Object.configureLaunchAssetsAsync (/@expo/xdl@56.0.1-rc.1/src/detach/IosLaunchScreen.js:225:11)
  pid: 39079,
  output: [ '', '' ],
  stdout: '',
  stderr: '',
  status: 1,
  signal: null }
Jul 23 11:12:24 turtle[38996] INFO:  Cleaning up iOS...
  platform: "ios"
  buildPhase: "configuring NSBundle"
Jul 23 11:12:24 turtle[38996] ERROR: Error: ibtool exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/Jonathan/Projecten/[REDACTED]/[REDACTED]/[REDACTED]/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
    ...
    at spawnAsync (/Users/Jonathan/Projecten/[REDACTED]/[REDACTED]/[REDACTED]/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnAsyncThrowError (/@expo/xdl@56.0.1-rc.1/src/detach/ExponentTools.ts:131:19)
    at Object.configureLaunchAssetsAsync (/@expo/xdl@56.0.1-rc.1/src/detach/IosLaunchScreen.js:225:11)
  platform: "ios"
Jul 23 11:12:24 turtle[38996] INFO:  delete keychain...
  platform: "ios"
  buildPhase: "deleting keychain"
Jul 23 11:12:24 turtle[38996] INFO:  deleting keychain...
  platform: "ios"
  buildPhase: "deleting keychain"
Jul 23 11:12:30 turtle[38996] INFO:  done deleting keychain
  platform: "ios"
  buildPhase: "deleting keychain"
Jul 23 11:12:30 turtle[38996] ERROR: Failed to build standalone app
  err: Error: ibtool exited with non-zero code: 1
      at ChildProcess.completionListener (/Users/Jonathan/Projecten/[REDACTED]/[REDACTED]/[REDACTED]/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:286:20)
      at ChildProcess.emit (events.js:198:13)
      at ChildProcess.EventEmitter.emit (domain.js:448:20)
      at maybeClose (internal/child_process.js:982:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
      ...
      at spawnAsync (/Users/Jonathan/Projecten/[REDACTED]/[REDACTED]/[REDACTED]/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at spawnAsyncThrowError (/@expo/xdl@56.0.1-rc.1/src/detach/ExponentTools.ts:131:19)
      at Object.configureLaunchAssetsAsync (/@expo/xdl@56.0.1-rc.1/src/detach/IosLaunchScreen.js:225:11)
  platform: "ios"
</pre>
</details>

### Environment

<details>
<pre>
  Expo CLI 3.0.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
</pre>
</details>

**Comment by jhogervorst** [comment]
As the output indicated some error with creating a iOS 12.4 simulator, I tried manually starting the iOS Simulator from Xcode 10.3. After that, the build command ran fine.

I suppose the iOS 12.4 simulator (which is new in Xcode 10.3) somehow only got initialised after running the iOS Simulator app?

Maybe turtle-cli could detect such a situation, and provide a useful error message?

**Comment by dsokal** [comment]
Hello @jhogervorst,

thanks for reporting. Please correct me if I'm wrong, you upgraded Xcode to 10.3 and you hadn't run it before running the turtle-cli command. The command failed but when you ran the new simulator version (that came out with Xcode 10.3) and you probably agreed to the license agreements, the issue went away, right?

Please check out the docs - https://docs.expo.io/versions/v33.0.0/distribution/turtle-cli/#for-ios-builds
> - Xcode (version 9.4.1 or newer) - make sure you have run it at least once and you have agreed to the license agreements. Alternatively you can run `sudo xcodebuild -license`.

I'll check whether it's possible to detect if someone has agreed to the license agreements programmatically, so we could print some meaningful error message.

**Comment by jhogervorst** [comment]
@dsokal If I recall correctly, I did open Xcode 10.3 before running the turtle-cli command. However, I did not open the included Simulator. I’m 90% sure about this 😕

**Comment by dsokal** [comment]
Sorry to say but I'm 98.9% sure you didn't :P I'll try to verify that on a fresh install of macOS.
