### ISSUE TITLE
com.google.android.geo.API_KEY missing in AndroidManifest.xml

### ISSUE THREAD

**Issue by borgogelli** [expo/turtle#122]
here a fragment of my app.json:
```

        "ios": {
            "config": {
                "googleSignIn": {
                    "reservedClientId": "com.googleusercontent.apps.XXXXXXX"
                },
                "googleMapsApiKey": "MY-APIKEY"
            },
        },
        "android": {
            "googleServicesFile": "./google-services.json",
            "config": {
                "googleMaps": {
                    "apiKey": "MY-OTHER-APIKEY"
                }
            },
        }, 
```

If I build the app...

1) using turtle-cli@0.8.3 the generated AndroidManifest.xml file contains:
```
<meta-data
    android:name="com.google.android.geo.API_KEY"
    android:value="EXPO-DEFAULT-APIKEY" />
```

2) using turtle-cli@0.8.11 the generated AndroidManifest.xml contains no value for com.google.android.geo.API_KEY

3) using expo-cli the result is exactly what I expect

```
<meta-data
    android:name="com.google.android.geo.API_KEY"
    android:value="MY-APIKEY" />
```

**Comment by dsokal** [comment]
Hello @borgogelli,
which Expo SDK version are you using?

**Comment by borgogelli** [comment]
v33.0.X

**Comment by dsokal** [comment]
@borgogelli sorry for the inconvenience, this should be fixed in the next release of `turtle-cli` - https://github.com/expo/turtle/pull/123/files

**Comment by borgogelli** [comment]
Thank you.

**Comment by dthuering** [comment]
I had to add the `--config` flag pointing to the correct config json file.
