### ISSUE TITLE
Android blank maps

### ISSUE THREAD

**Issue by gyurka00** [expo/turtle#126]
### New Issue Checklist

- [x] Updated turtle-cli to the latest version (`yarn global add turtle-cli` or `npm install --global turtle-cli`).
- [x] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [x] I read [docs.expo.io](https://docs.expo.io) (Managed Workflow > Distributing Your App).
- [x] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).
- [x] **I enclosed the complete output when running turtle, including the stack trace and command used.**

### Issue Description
With the latest turtle the local build and the cloud build were success, but the built app just showing the blank map.
![image](https://user-images.githubusercontent.com/15729125/62197159-a6abb480-b37f-11e9-9562-3c95e9d5b8b8.png)

##### Command executed
turtle build:android --keystore-path <PATH> --keystore-alias <ALIAS> -c <CONFIG PATH> --type apk  -u <USER> -p <PASS> -d <OUTPUT PATH> -m 'release'

##### Complete output when running turtle, including the stack trace and command used

<details>
  <pre> Jul 31 09:39:46 turtle[30230] INFO:  copied build to <SOME PATH>/signed.apk
  platform: "android"
  buildPhase: "copying build artifact"
 </pre>
</details>

**Comment by dsokal** [comment]
Hello @gyurka00,
thanks for reporting. Could you please provide the **complete** output from turtle-cli? You only sent one line of logs. What Expo SDK version are you using?

**Comment by gyurka00** [comment]
I tried with Expo sdk: 33.0.0 and with Expo sdk: 32.0.0 and both build were success, but didn't show the map.
The builds from a week ago showing the map correctly (it braked when the new turtle arrived).
[log.txt](https://github.com/expo/turtle/files/3450950/log.txt)

**Comment by dsokal** [comment]
@gyurka00 are you sure your Google Maps API key is valid and your android package is allowed to use it?

**Comment by dsokal** [comment]
I've just built an app with `MapView` using the latest version of turtle-cli and it works fine.
