### ISSUE TITLE
Cant setup / build with turtle-cli

### ISSUE THREAD

**Issue by ShortByte** [expo/turtle#134]
Hello guys,

I'm currently trying to get Turtle-Cli to work. Unfortunately I always get this error as soon as it goes to the decompressing of Androdi NDK. Does anyone have any idea what I'm doing wrong?

Error: 
```
root@vps-2:/home/expo/app# turtle setup:android
Aug 22 02:09:37 turtle[15878] INFO:  Downloading Android SDK
  platform: "android"
  buildPhase: "setting up environment"
downloading [==================  ] 91% 0.3sAug 22 02:09:40 turtle[15878] INFO:  Decompressing Android SDK
  platform: "android"
  buildPhase: "setting up environment"
Aug 22 02:09:48 turtle[15878] INFO:  Configuring Android SDK, this may take a while
  platform: "android"
  buildPhase: "setting up environment"
Aug 22 02:11:28 turtle[15878] INFO:  Android SDK installed and configured successfully
  platform: "android"
  buildPhase: "setting up environment"
Aug 22 02:11:28 turtle[15878] INFO:  Downloading Android NDK
  platform: "android"
  buildPhase: "setting up environment"
downloading [====================] 99% 0.2sAug 22 02:11:47 turtle[15878] INFO:  Decompressing Android NDK
  platform: "android"
  buildPhase: "setting up environment"
Killed <---- 
root@vps-2:/home/expo/app# 
```

System:
Ubuntu 18.04 (Virtual machine)
Node Version: v10.16.3
npm Version: 6.9.0
yarn Version: 1.17.3
Java Version: 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10

**Comment by Cyborion** [comment]
How much RAM do you have assigned to your VM? In my case RAM usage sometimes is quite high.

**Comment by panlei09** [comment]
I also met, is your problem solved?

**Comment by panlei09** [comment]
I also met, is your problem solved?

**Comment by dbyst** [comment]
Same issue

**Comment by virus2016** [comment]
Same here

**Comment by virus2016** [comment]
Hey guys, 

It's a memory issue. Increasing the memory will fix it.

Thanks,

**Comment by dsokal** [comment]
@virus2016 is right. You should increase the memory limit.

**Comment by henrypalacios** [comment]
> Hey guys,
> 
> It's a memory issue. Increasing the memory will fix it.
> 
> Thanks,

Hi @virus2016. Could you guide me on how to increase the memory limit?

I tried with Global variable.
```NODE_OPTIONS=--max_old_space_size=4096```

but not worked.

**Comment by chlsmith** [comment]
I'm having this issue, too, and I don't see how to set that.   Tips?

**Comment by chlsmith** [comment]
found it.   I just added the resources to my docker configuration.   I did have to go to 8 GB, though.   
![image](https://user-images.githubusercontent.com/10780098/73177257-8c5b5500-40dc-11ea-8559-9fd0838c1f6e.png)

**Comment by maxdeepfield** [comment]
this issue still exists. how to fix it right way?

**Comment by shahidcodes** [comment]
Any way to solve this? I have 16 GB but still, it is stuck

**Comment by maxdeepfield** [comment]
I was able to install turtle-cli sucessfully on Ubuntu 20.04 virtual machine with 16 GB ram and nodejs 14.
