### ISSUE TITLE
Cannot build IPA, problem with channel

### ISSUE THREAD

**Issue by sobi3ch** [expo/turtle#135]
Please check my question here

https://stackoverflow.com/questions/57675415/whats-wrong-with-my-turtle-release-channel

**Comment by dsokal** [comment]
Hi @sobi3ch, 
Have you published your app to the `testing` release channel prior to running the build? `turtle-cli` doesn't cover this step, so you should run `expo publish --release-channel testing` just before `turtle build:ios ...`.

**Comment by sobi3ch** [comment]
Hi @dsokal, thank you for quick response. I'll try it and let you know.
