### ISSUE TITLE
Cannot setup turtle-cli for android

### ISSUE THREAD

**Issue by kavofa** [expo/turtle#139]
### New Issue Checklist

- [x] Updated turtle-cli to the latest version (`yarn global add turtle-cli` or `npm install --global turtle-cli`).
- [x] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [x] I read [docs.expo.io](https://docs.expo.io) (Managed Workflow > Distributing Your App).
- [x] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).

### Issue Description
Error when setting up turtle-cli for building for android

##### Command executed
`turtle setup:android --sdk-version 34.0.0`

##### Complete output when running turtle, including the stack trace and command used

<details>
  <pre>
Sep 19 22:13:04 turtle[1350] INFO:  shell app for SDK 34.0.0 doesn't exist, downloading...
  platform: "android"
  buildPhase: "setting up environment"
downloading [====================] 99% 0.3sSep 19 22:16:21 turtle[1350] INFO:  shell app has been downloaded
  platform: "android"
  buildPhase: "setting up environment"
Sep 19 22:16:21 turtle[1350] INFO:  extracting shell app (this may take a while)...
  platform: "android"
  buildPhase: "setting up environment"
Sep 19 22:16:36 turtle[1350] INFO:  shell app extracted
  platform: "android"
  buildPhase: "setting up environment"
Sep 19 22:16:36 turtle[1350] INFO:  installing dependencies in /Users/username/.turtle/workingdir/android/sdk34 directory...
  platform: "android"
  buildPhase: "setting up environment"
Sep 19 22:17:11 turtle[1350] INFO:  > @expo/traveling-fastlane-darwin@1.9.11 preinstall /Users/username/.turtle/workingdir/android/sdk34/node_modules/@expo/traveling-fastlane-darwin
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Sep 19 22:17:11 turtle[1350] INFO:  > node platform.js
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Sep 19 22:17:11 turtle[1350] INFO:  > fsevents@1.2.9 install /Users/username/.turtle/workingdir/android/sdk34/node_modules/fsevents
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Sep 19 22:17:11 turtle[1350] INFO:  > node install
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Sep 19 22:17:12 turtle[1350] INFO:  node-pre-gyp
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:12 turtle[1350] INFO:
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:12 turtle[1350] INFO:  WARN Using request for node-pre-gyp https download
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:13 turtle[1350] INFO:  [fsevents] Success: "/Users/username/.turtle/workingdir/android/sdk34/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Sep 19 22:17:13 turtle[1350] INFO:  > iltorb@2.4.3 install /Users/username/.turtle/workingdir/android/sdk34/node_modules/iltorb
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Sep 19 22:17:13 turtle[1350] INFO:  > node ./scripts/install.js || node-gyp rebuild
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Sep 19 22:17:13 turtle[1350] INFO:  info
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:13 turtle[1350] INFO:
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:13 turtle[1350] INFO:  looking for cached prebuild @ /Users/username/.npm/_prebuilds/db4ff3-iltorb-v2.4.3-node-v64-darwin-x64.tar.gz
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:13 turtle[1350] INFO:  info
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:13 turtle[1350] INFO:   found cached prebuild
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:13 turtle[1350] INFO:  info unpacking @ /Users/username/.npm/_prebuilds/db4ff3-iltorb-v2.4.3-node-v64-darwin-x64.tar.gz
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:13 turtle[1350] INFO:  info
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:13 turtle[1350] INFO:   unpack resolved to /Users/username/.turtle/workingdir/android/sdk34/node_modules/iltorb/build/bindings/iltorb.node
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:13 turtle[1350] INFO:  info
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:13 turtle[1350] INFO:   unpack required /Users/username/.turtle/workingdir/android/sdk34/node_modules/iltorb/build/bindings/iltorb.node successfully
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:13 turtle[1350] INFO:  info install Successfully installed iltorb binary!
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:13 turtle[1350] INFO:  > sharp@0.22.1 install /Users/username/.turtle/workingdir/android/sdk34/node_modules/sharp
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Sep 19 22:17:13 turtle[1350] INFO:  > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Sep 19 22:17:16 turtle[1350] INFO:  info
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:16 turtle[1350] INFO:
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:16 turtle[1350] INFO:  sharp Using cached /Users/username/.npm/_libvips/libvips-8.7.4-darwin-x64.tar.gz
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:17 turtle[1350] INFO:  > core-js@2.6.9 postinstall /Users/username/.turtle/workingdir/android/sdk34/node_modules/core-js
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Sep 19 22:17:17 turtle[1350] INFO:  > node scripts/postinstall || echo "ignore"
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Sep 19 22:17:17 turtle[1350] INFO:  Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Sep 19 22:17:17 turtle[1350] INFO:  The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Sep 19 22:17:17 turtle[1350] INFO:  > https://opencollective.com/core-js
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Sep 19 22:17:17 turtle[1350] INFO:  > https://www.patreon.com/zloirock
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Sep 19 22:17:17 turtle[1350] INFO:  Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Sep 19 22:17:17 turtle[1350] INFO:  > react-native-unimodules@0.5.4 postinstall /Users/username/.turtle/workingdir/android/sdk34/node_modules/react-native-unimodules
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Sep 19 22:17:17 turtle[1350] INFO:  > node ./scripts/postinstall.js
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Sep 19 22:17:17 turtle[1350] INFO:  Successfully installed react-native-unimodules. This package contains core unimodules that are commonly depended on by other unimodules. You will need to configure your project before using other unimodules like expo-camera, expo-media-library and others.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Sep 19 22:17:17 turtle[1350] INFO:  See configuration guide:
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Sep 19 22:17:17 turtle[1350] INFO:    https://www.npmjs.com/package/react-native-unimodules/v/0.5.4
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Sep 19 22:17:19 turtle[1350] INFO:  > @expo/expo@1.4.0 postinstall /Users/username/.turtle/workingdir/android/sdk34
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Sep 19 22:17:19 turtle[1350] INFO:  > expo-yarn-workspaces check-workspace-dependencies && rm -rf node_modules/babel-jest/node_modules/babel-core
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Sep 19 22:17:19 turtle[1350] INFO:  Could not run yarn: spawnSync yarn ENOENT
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:19 turtle[1350] INFO:  Couldn't generate Yarn's workspace root information.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:19 turtle[1350] INFO:  > @expo/expo@1.4.0 prepare /Users/username/.turtle/workingdir/android/sdk34
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Sep 19 22:17:19 turtle[1350] INFO:  > yarn workspace expo prepare
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Sep 19 22:17:19 turtle[1350] INFO:  sh: yarn: command not found
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:19 turtle[1350] INFO:  npm
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:19 turtle[1350] INFO:   ERR! file sh
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:19 turtle[1350] INFO:  npm ERR! code
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:19 turtle[1350] INFO:   ELIFECYCLE
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:19 turtle[1350] INFO:  npm ERR!
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:19 turtle[1350] INFO:  errno ENOENT
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:19 turtle[1350] INFO:  npm ERR! syscall spawn
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:19 turtle[1350] INFO:  npm
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:19 turtle[1350] INFO:   ERR! @expo/expo@1.4.0 prepare: `yarn workspace expo prepare`
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:19 turtle[1350] INFO:  npm ERR! spawn ENOENT
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:19 turtle[1350] INFO:  npm ERR!
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:19 turtle[1350] INFO:  npm ERR! Failed at the @expo/expo@1.4.0 prepare script.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:19 turtle[1350] INFO:  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:19 turtle[1350] INFO:  npm ERR!
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:19 turtle[1350] INFO:   A complete log of this run can be found in:
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:19 turtle[1350] INFO:  npm ERR!     /Users/username/.npm/_logs/2019-09-19T20_17_19_696Z-debug.log
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Sep 19 22:17:19 turtle[1350] ERROR: Failed to setup environment for android builds
  err: Error: npm exited with non-zero code: 1
      at ChildProcess.completionListener (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:277:13)
      at ChildProcess.emit (events.js:189:13)
      at ChildProcess.EventEmitter.emit (domain.js:441:20)
      at maybeClose (internal/child_process.js:970:16)
      at Socket.stream.socket.on (internal/child_process.js:389:11)
      at Socket.emit (events.js:189:13)
      at Socket.EventEmitter.emit (domain.js:441:20)
      at Pipe._handle.close (net.js:600:12)
      ...
      at spawnAsync (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at Object.spawnAsyncThrowError (/@expo/xdl@56.2.1/src/detach/ExponentTools.ts:131:19)
      at _installNodeModules (/usr/local/lib/node_modules/turtle-cli/src/bin/setup/android/index.ts:91:23)
  platform: "android"
</pre>
</details>

### Environment
<details>
  <pre>
  Expo CLI 3.0.10 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.0.10
</pre>
</details>

**Comment by artalat** [comment]
Any updates or workaround to get bypass this issue?

**Comment by kavofa** [comment]
I had to install yarn. But I have an other error now when building an apk. https://forums.expo.io/t/android-build-failed-turtle-cli/28029

**Comment by wkozyra95** [comment]
I'm assuming that installing yarn solved this problem, if not please reopen this issue
