### ISSUE TITLE
Apple upload Error with new application loader

### ISSUE THREAD

**Issue by calebbriggs** [expo/turtle#141]
ERROR ITMS-90596: "Invalid Bundle. The asset catalog at 'Payload/ExpoKitApp.app/GoogleMaps.bundle/GMSCoreResources.bundle/Assets.car' can't be processed. Rebuild your app, and all included extensions and frameworks, with the latest GM version of Xcode and resubmit."

**Comment by calebbriggs** [comment]
Expo SDK 35

**Comment by wkozyra95** [comment]
turtle-cli is using your local xcode and all the prebuilt parts were built using GM 2, so i"m guessing that you didn't update your xcode.

**Comment by calebbriggs** [comment]
I am on xcode 11, which is the current version. I get the same error when I use the expo build commands and download the IPA which very well could be n my end still just trying to get to the root. Here is my dependencies

`"aws-amplify": "^1.1.6",
    "expo": "^35.0.0",
    "expo-camera": "~7.0.0",
    "expo-google-app-auth": "^7.0.0",
    "expo-google-sign-in": "~7.0.0",
    "expo-jwt": "^1.1.0",
    "expo-permissions": "~7.0.0",
    "graphql-request": "^1.8.2",
    "lodash": "^4.17.11",
    "md5": "^2.2.1",
    "moment": "^2.22.2",
    "pubsub-js": "^1.7.0",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-elements": "^0.19.1",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-picker-select": "^5.0.1",
    "react-native-popup-menu": "^0.14.0",
    "react-native-reanimated": "~1.2.0",
    "react-navigation": "^4.0.6",
    "react-navigation-stack": "^1.8.0"`

**Comment by calebbriggs** [comment]
Ok I reverted xcode back to 10.3 and it worked, thanks for your help
