### ISSUE TITLE
Android build keystore and Installing on device parse error

### ISSUE THREAD

**Issue by virus2016** [expo/turtle#143]
### Question Subject

Trying to build a standalone app via turtle with custom keystore. Build succeeds however I get a parse error when trying to install on an Android. If I use expo to build, it works perfect.

#### Question Description

How do you create a keystore?

I am trying to do the following: 

```
keytool -genkeypair -dname "CN=com.test.app, OU=App, O=random, L=Unknown, ST=Unknown, C=Unknown" -keypass WNSIWEAADDSDVBKVBDQTOGZKLBIPSPTW -alias com.test.app -keysize 2048 -keyalg RSA -validity 10000 -noprompt -keystore android.keystore -storepass MPICJFBRBSTFJMXQSZCHQXZOAVGHRFJI -storetype JKS
```

How do you use the keystore in turtle?

```
turtle build:android --public-url https://[URL]/android-index.json  --keystore-path ./android.keystore --keystore-alias 'com.test.app' -o test.apk
```

Builds fine but has a parse error

![WhatsApp Image 2019-09-27 at 14 04 38](https://user-images.githubusercontent.com/11227384/65771301-ce28be80-e12f-11e9-849a-ea2451c6b982.jpeg)

**Comment by dsokal** [comment]
You changed the output filename to `.apk`, but the default is `.aab`.
If you wish to build an `.apk` file, you should pass `--type apk` to the `turtle build:android` command.

**Comment by virus2016** [comment]
Just found that out @dsokal,

Thanks again!
