### ISSUE TITLE
Turtle on Travis Hangs at App Signing Step

### ISSUE THREAD

**Issue by Jonathan-Navagis** [expo/turtle#146]
Expo Version: 33.0.0
Turtle Version: 0.12.3

I'm running the turtle in travis with the following command:
`turtle build:ios --team-id $EXPO_APPLE_TEAM_ID --dist-p12-path $CERT_PATH --provisioning-profile-path $PROVISIONING_PROFILE_PATH -o $ARTIFACT_PATH`

and the build continues as normal until it gets past creating the plist file in the build, then hangs after the following lines:

```
Oct 11 12:20:25 turtle[74595] INFO:  INFO [2019-10-11 12:20:25.86]: ▸ +xcodebuild -exportArchive -exportOptionsPlist /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/gym_config20191011-74669-xhhato.plist -archivePath /private/tmp/turtle/510483cf-515c-437d-bee2-273c4447d7e8/archive.xcarchive -exportPath /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/gym_output20191011-74669-iiih4d 'OTHER_CODE_SIGN_FLAGS=--keychain /private/tmp/xdl/71ebde70-ec21-11e9-80bb-3930307ea084.keychain'

  platform: "ios"

  buildPhase: "building and signing IPA"

  source: "stdout"

Oct 11 12:20:26 turtle[74595] INFO:  INFO [2019-10-11 12:20:26.62]: ▸ 2019-10-11 12:20:26.626 xcodebuild[74853:110486] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/ExpoKitApp_2019-10-11_12-20-26.624.xcdistributionlogs'.

  platform: "ios"

  buildPhase: "building and signing IPA"

  source: "stdout"
```

It's strange because It's worked fine up and until I started using fastlane's `match` in order to automate our key sharing, could expo's use of `gym` interact with a manual fastlane installation?

Not sure where to look from here, as there's no errors anywhere in the logs...

**Comment by dsokal** [comment]
Could you please share some steps on how to reproduce this issue? Thanks!
Also, please fill out the issue template to avoid further questions.

**Comment by dsokal** [comment]
Hi, 
I'm closing the issue because of inactivity. Please let me know if the problem still exists.
