### ISSUE TITLE
turtle: Process exited with non-zero code

### ISSUE THREAD

**Issue by DenzilGovender** [expo/turtle#148]
Hi,

I'm trying to build a stand alone app using the turtle cli on Azure DevOps. I'm using a hosted agent ubuntu 16.04

I'm getting an error when running the following command.

turtle build:android -u XXXXXXX -p XXXXXX --keystore-path ./androidKey.jks --keystore-alias "XXXXXXX" -t apk --release-channel deployment

Please see logs below. Please can you assist. Thanks

Oct 20 20:32:55 turtle[5076] ERROR: [31mError: ./gradlew exited with non-zero code: 1[39m
[31m    at ChildProcess.completionListener (/usr/local/share/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)[39m
[31m    at Object.onceWrapper (events.js:286:20)[39m
[31m    at ChildProcess.emit (events.js:198:13)[39m
[31m    at ChildProcess.EventEmitter.emit (domain.js:448:20)[39m
[31m    at maybeClose (internal/child_process.js:982:16)[39m
[31m    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)[39m
[31m    ...[39m
[31m    at spawnAsync (/usr/local/share/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)[39m
[31m    at spawnAsyncThrowError (/@expo/xdl@56.2.2-alpha.2/src/detach/ExponentTools.ts:131:19)[39m
[31m    at buildShellAppAsync (/@expo/xdl@56.2.2-alpha.2/src/detach/AndroidShellApp.js:1147:11)[39m
[31m  platform: "android"[39m
Oct 20 20:32:55 turtle[5076] ERROR: [31mFailed to build standalone app[39m
[31m  err: Error: ./gradlew exited with non-zero code: 1[39m
[31m      at ChildProcess.completionListener (/usr/local/share/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)[39m
[31m      at Object.onceWrapper (events.js:286:20)[39m
[31m      at ChildProcess.emit (events.js:198:13)[39m
[31m      at ChildProcess.EventEmitter.emit (domain.js:448:20)[39m
[31m      at maybeClose (internal/child_process.js:982:16)[39m
[31m      at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)[39m
[31m      ...[39m
[31m      at spawnAsync (/usr/local/share/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)[39m
[31m      at spawnAsyncThrowError (/@expo/xdl@56.2.2-alpha.2/src/detach/ExponentTools.ts:131:19)[39m
[31m      at buildShellAppAsync (/@expo/xdl@56.2.2-alpha.2/src/detach/AndroidShellApp.js:1147:11)[39m
[31m  platform: "android"[39m
##[error]Bash exited with code '1'.

**Comment by dsokal** [comment]
Hi, 
please share the full log output from turtle-cli. The excerpt you shared with us is meaningless.
Generally, I recommend you to fill out the issue template to avoid further questions.

**Comment by dsokal** [comment]
Hi, 
I'm closing the issue because of inactivity. Please let me know if the problem still exists.
