### ISSUE TITLE
Error: ./configureAndroidSdk.sh exited with non-zero code: 1 on android setup

### ISSUE THREAD

**Issue by BrickmanRodrigo** [expo/turtle#153]
### New Issue Checklist

- [x] Updated turtle-cli to the latest version (`yarn global add turtle-cli` or `npm install --global turtle-cli`).
- [x] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [x] I read [docs.expo.io](https://docs.expo.io) (Managed Workflow > Distributing Your App).
- [x] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).
- [x] **I enclosed the complete output when running turtle, including the stack trace and command used.**

### Issue Description
configureAndroidSdk.sh exited with non-zero code when I tried to run turtle setup:android.

Edit: Already tried reinstalling turtle, node and expo and still fails

##### Command executed
turtle setup:android

##### Complete output when running turtle, including the stack trace and command used

<details>
  <pre>Oct 25 09:39:38 turtle[7814] INFO:  Downloading Android SDK
  platform: "android"
  buildPhase: "setting up environment"
downloading [=================== ] 95% 0.6sOct 25 09:39:52 turtle[7814] INFO:  Decompressing Android SDK
  platform: "android"
  buildPhase: "setting up environment"
Oct 25 09:39:54 turtle[7814] INFO:  Configuring Android SDK, this may take a while
  platform: "android"
  buildPhase: "setting up environment"
Oct 25 09:39:55 turtle[7814] INFO:  Exception in thread "main" 
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:  java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:  Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      ... 5 more
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:  Exception in thread "main" 
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:  java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:  Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      ... 5 more
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:  Exception in thread "main" 
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:  java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:  Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      ... 5 more
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:  Exception in thread "main" 
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:  java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:  Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      ... 5 more
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:  Exception in thread "main" 
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:  java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:  Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] INFO:      ... 5 more
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 25 09:39:55 turtle[7814] ERROR: Failed to setup environment for android builds
  err: Error: ./configureAndroidSdk.sh exited with non-zero code: 1
      at ChildProcess.completionListener (/home/rodrigob/.nvm/versions/node/v12.12.0/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:300:26)
      at ChildProcess.emit (events.js:210:5)
      at ChildProcess.EventEmitter.emit (domain.js:476:20)
      at maybeClose (internal/child_process.js:1021:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
      ...
      at spawnAsync (/home/rodrigob/.nvm/versions/node/v12.12.0/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at Object.spawnAsyncThrowError (/@expo/xdl@56.2.2-alpha.2/src/detach/ExponentTools.ts:131:19)
      at _configureSdk (/home/rodrigob/.nvm/versions/node/v12.12.0/lib/node_modules/turtle-cli/src/bin/setup/android/sdk.ts:54:23)
      at Object.ensureAndroidSDKIsPresent [as default] (/home/rodrigob/.nvm/versions/node/v12.12.0/lib/node_modules/turtle-cli/src/bin/setup/android/sdk.ts:34:7)
      at prepareAndroidEnv (/home/rodrigob/.nvm/versions/node/v12.12.0/lib/node_modules/turtle-cli/src/bin/setup/android/index.ts:56:21)
      at Object.setup [as default] (/home/rodrigob/.nvm/versions/node/v12.12.0/lib/node_modules/turtle-cli/src/bin/setup/android/index.ts:44:3)
      at Object.setup [as default] (/home/rodrigob/.nvm/versions/node/v12.12.0/lib/node_modules/turtle-cli/src/bin/setup/setup.ts:15:12)
      at setupAction (/home/rodrigob/.nvm/versions/node/v12.12.0/lib/node_modules/turtle-cli/src/bin/commands/setup.ts:33:5)
      at /home/rodrigob/.nvm/versions/node/v12.12.0/lib/node_modules/turtle-cli/src/bin/commands/setup.ts:22:40
      at Command.<anonymous> (/home/rodrigob/.nvm/versions/node/v12.12.0/lib/node_modules/turtle-cli/src/bin/index.ts:23:12)
  platform: "android" </pre>
</details>

### Environment

<details>
  <pre>  Expo CLI 3.4.1 environment info:
    System:
      OS: Linux 4.4 Ubuntu 16.04.6 LTS (Xenial Xerus)
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 12.12.0 - ~/.nvm/versions/node/v12.12.0/bin/node
      Yarn: 1.17.3 - /usr/bin/yarn
      npm: 6.11.3 - ~/.nvm/versions/node/v12.12.0/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ~3.11.0 => 3.11.3 
    npmGlobalPackages:
      expo-cli: 3.4.1</pre>
</details>

**Comment by dsokal** [comment]
Hi!
Which java version do you have? I guess it's not 8?

https://stackoverflow.com/questions/46402772/failed-to-install-android-sdk-java-lang-noclassdeffounderror-javax-xml-bind-a

**Comment by BrickmanRodrigo** [comment]
Yes, I do have java 8

Here is my output of java -version:
<details>
<pre>openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)</pre>
</details>

**Comment by dsokal** [comment]
Could you please try to set the `JAVA_OPTS` as follows and then try to run `turtle setup:android` again?
```bash
$ export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'
$ turtle setup:android
```

**Comment by BrickmanRodrigo** [comment]
Tried that and the error log changed a little, here it is:

<details>
<pre>Oct 25 10:02:29 turtle[8787] INFO:  Downloading Android SDK
  platform: "android"
  buildPhase: "setting up environment"
downloading [====================] 99% 0.0sOct 25 10:02:43 turtle[8787] INFO:  Decompressing Android SDK
  platform: "android"
  buildPhase: "setting up environment"
Oct 25 10:02:45 turtle[8787] INFO:  Configuring Android SDK, this may take a while
  platform: "android"
  buildPhase: "setting up environment"
Oct 25 10:02:46 turtle[8787] INFO:  Error occurred during initialization of boot layer
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Oct 25 10:02:46 turtle[8787] INFO:  java.lang.module.FindException: Module java.se.ee not found
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Oct 25 10:02:46 turtle[8787] INFO:  Error occurred during initialization of boot layer
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Oct 25 10:02:46 turtle[8787] INFO:  java.lang.module.FindException: Module java.se.ee not found
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Oct 25 10:02:46 turtle[8787] INFO:  Error occurred during initialization of boot layer
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Oct 25 10:02:46 turtle[8787] INFO:  java.lang.module.FindException: Module java.se.ee not found
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Oct 25 10:02:46 turtle[8787] INFO:  Error occurred during initialization of boot layer
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Oct 25 10:02:46 turtle[8787] INFO:  java.lang.module.FindException: Module java.se.ee not found
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Oct 25 10:02:46 turtle[8787] ERROR: Failed to setup environment for android builds
  err: Error: ./configureAndroidSdk.sh exited with non-zero code: 1
      at ChildProcess.completionListener (/home/rodrigob/.nvm/versions/node/v12.12.0/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:300:26)
      at ChildProcess.emit (events.js:210:5)
      at ChildProcess.EventEmitter.emit (domain.js:476:20)
      at maybeClose (internal/child_process.js:1021:16)
      at Socket.<anonymous> (internal/child_process.js:430:11)
      at Socket.emit (events.js:210:5)
      at Socket.EventEmitter.emit (domain.js:476:20)
      at Pipe.<anonymous> (net.js:658:12)
      ...
      at spawnAsync (/home/rodrigob/.nvm/versions/node/v12.12.0/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at Object.spawnAsyncThrowError (/@expo/xdl@56.2.2-alpha.2/src/detach/ExponentTools.ts:131:19)
      at _configureSdk (/home/rodrigob/.nvm/versions/node/v12.12.0/lib/node_modules/turtle-cli/src/bin/setup/android/sdk.ts:54:23)
      at Object.ensureAndroidSDKIsPresent [as default] (/home/rodrigob/.nvm/versions/node/v12.12.0/lib/node_modules/turtle-cli/src/bin/setup/android/sdk.ts:34:7)
      at prepareAndroidEnv (/home/rodrigob/.nvm/versions/node/v12.12.0/lib/node_modules/turtle-cli/src/bin/setup/android/index.ts:56:21)
      at Object.setup [as default] (/home/rodrigob/.nvm/versions/node/v12.12.0/lib/node_modules/turtle-cli/src/bin/setup/android/index.ts:44:3)
      at Object.setup [as default] (/home/rodrigob/.nvm/versions/node/v12.12.0/lib/node_modules/turtle-cli/src/bin/setup/setup.ts:15:12)
      at setupAction (/home/rodrigob/.nvm/versions/node/v12.12.0/lib/node_modules/turtle-cli/src/bin/commands/setup.ts:33:5)
      at /home/rodrigob/.nvm/versions/node/v12.12.0/lib/node_modules/turtle-cli/src/bin/commands/setup.ts:22:40
      at Command.<anonymous> (/home/rodrigob/.nvm/versions/node/v12.12.0/lib/node_modules/turtle-cli/src/bin/index.ts:23:12)
  platform: "android"</pre></details>

**Comment by dsokal** [comment]
Are you completely sure you don't have multiple java versions installed on your system?
Please execute the following command and share the output:
```bash
$ sudo update-alternatives --config java
```

**Comment by BrickmanRodrigo** [comment]
I also have java 11, but in my alternatives I have the java 8 selected as default

Here is the output in case you need it:

<pre>Existen 2 opciones para la alternativa java (que provee /usr/bin/java).

  Selección   Ruta                                            Prioridad  Estado
------------------------------------------------------------
  0            /usr/lib/jvm/java-11-oracle/bin/java             1091      modo automático
  1            /usr/lib/jvm/java-11-oracle/bin/java             1091      modo manual
* 2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      modo manual

Press <enter> to keep the current choice[*], or type selection number:</pre>

**Comment by dsokal** [comment]
Could you please run one more command?
`$JAVA_HOME/bin/java -version`

**Comment by BrickmanRodrigo** [comment]
Yeah, I was just looking into that, my $JAVA_HOME was pointing to the java 11 directory. I changed it to the java 8 directory and it works fine.

Thanks for your help!

**Comment by Syedz15** [comment]
I am having the same issue: Please advise.
Feb 12 18:01:21 turtle[23808] ERROR: Failed to setup environment for android builds
  err: Error: ./configureAndroidSdk.sh exited with non-zero code: 1
      at ChildProcess.completionListener (/usr/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:286:20)
      at ChildProcess.emit (events.js:198:13)
      at ChildProcess.EventEmitter.emit (domain.js:448:20)
      at maybeClose (internal/child_process.js:982:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
      ...
      at spawnAsync (/usr/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at Object.spawnAsyncThrowError (/@expo/xdl@57.4.0/src/detach/ExponentTools.ts:132:19)
      at _configureSdk (/usr/lib/node_modules/turtle-cli/src/bin/setup/android/sdk.ts:54:23)
  platform: "android"
[root@ip-10-157-155-173 mobile-native]# sudo update-alternatives --config java

There is 1 program that provides 'java'.

  Selection    Command
-----------------------------------------------
*+ 1           java-1.8.0-openjdk.x86_64 (/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64/jre/bin/java)

Enter to keep the current selection[+], or type selection number:
[root@ip-10-157-155-173 mobile-native]# $JAVA_HOME/bin/java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

**Comment by shahiddhariwala** [comment]
Hi, I am facing this issue on WIndows,
![image](https://user-images.githubusercontent.com/32133607/93886869-9123e780-fd03-11ea-90de-92c9ad0a1d39.png)
