### ISSUE TITLE
Error occurred when build ios

### ISSUE THREAD

**Issue by brad0912** [expo/turtle#157]
Hi, I have an error message when I tried to build and sign ios file.

The error log as flow and the whole log on attach files:
[buildipa_errorlog.txt](https://github.com/expo/turtle/files/3787906/buildipa_errorlog.txt)

INFO [2019-10-30 16:15:40.63]: ▸ error: exportArchive: Code signing "ExpoKitApp.app" failed.
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"

INFO [2019-10-30 16:15:40.63]: ▸ Error Domain=IDEDistributionPipelineErrorDomain Code=0 "Code signing "ExpoKitApp.app" failed." UserInfo={NSLocalizedDescription=Code signing "ExpoKitApp.app" failed., NSLocalizedRecoverySuggestion=View distribution logs for more information.}
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stdout"

**Comment by dsokal** [comment]
Please check xcodebuild logs in `/var/folders/bd/xdk09svn73ld8nq1z7lv35g80000gn/T/ExpoKitApp_2019-10-30_16-15-32.332.xcdistributionlogs/IDEDistributionPipeline.log` and/or share this file with me.
You should learn more there.

**Comment by brad0912** [comment]
> Please check xcodebuild logs in `/var/folders/bd/xdk09svn73ld8nq1z7lv35g80000gn/T/ExpoKitApp_2019-10-30_16-15-32.332.xcdistributionlogs/IDEDistributionPipeline.log` and/or share this file with me.
> You should learn more there.

Hi, here is the file.
[IDEDistributionPipeline.log](https://github.com/expo/turtle/files/3788015/IDEDistributionPipeline.log)

**Comment by dsokal** [comment]
1. Please try to run xcode and then close it (make sure to accept all license agreements, etc.).
2. Make sure xcode is closed when you're executing `turtle build:ios` command.
3. If the above tips won't help please restart your Mac and try again.

**Comment by brad0912** [comment]
> 1. Please try to run xcode and then close it (make sure to accept all license agreements, etc.).
> 2. Make sure xcode is closed when you're executing `turtle build:ios` command.
> 3. If the above tips won't help please restart your Mac and try again.
> 
> Please also check https://stackoverflow.com/questions/24023639/xcode-command-usr-bin-codesign-failed-with-exit-code-1-errsecinternalcomponen

It works after I restart my Mac.
Thanks.
