### ISSUE TITLE
Can I provide my p8 certificate to turtle build:ios

### ISSUE THREAD

**Issue by AirEssY** [expo/turtle#159]
### Question Checklist

- [x] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [x] I read [docs.expo.io](https://docs.expo.io) (Managed Workflow > Distributing Your App).
- [x] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).

### Question Subject

using a p8 file with `turtle build:ios`

Doesn't seem to be in any documentation

#### Question Description

I’ve set up a CI pipeline in AzureDeops using turtle and it’s working great.
However I had a question, I don’t see how I can pass in any details regarding my p8 certificate?

turtle build:ios \
-u $(EXPO_CLI_USER) -p $(EXPO_CLI_PASSWORD)
  --team-id YOUR_TEAM_ID \
  --dist-p12-path /path/to/your/dist/cert.p12 \
  --provisioning-profile-path /path/to/your/provisioning/profile.mobileprovision
  --public-url http://127.0.0.1:8000/ios-index.json

Am I missing something here? Or will it just use my p8 correctly due to the fact that I’m passing in the expo creds?

**Comment by tell-y** [comment]
I'm also wondering if we should pass p8 path when we use own APN.
Is there only way to pass the p8 path at running `expo build:ios` ?

**Comment by tell-y** [comment]
I missed the forum link.
[https://forums.expo.io/t/can-i-provide-my-p8-certificate-to-turtle-build-ios/29843/2](https://forums.expo.io/t/can-i-provide-my-p8-certificate-to-turtle-build-ios/29843/2)
It seems we can use `expo credentials:manager` to manage APN after building.

**Comment by dsokal** [comment]
Hello guys,
Sorry for the super-late response. Turtle doesn't need your Push Notification Key to build the app. It's only needed by our push server to send notifications to your app. It's completely unrelated to the build process.
And yes, you can use `expo credentials:manager` to upload the key.
