### ISSUE TITLE
Turtle cache on circle CI

### ISSUE THREAD

**Issue by teod** [expo/turtle#16]
I am using fastlane to deliver the assets directly to the testflight and play store beta. This means that we increment `expo.android.versionCode` and `expo.ios.buildNumber` from app.json on each build, unfortunately restoring cache the way it's described in the circle ci [example config](
https://github.com/expo/turtle-cli-example/blob/master/.circleci/config.yml) disregards these values, is there a way I can keep the turtle cache and changing app.json on each buid ?

**Comment by dsokal** [comment]
Hello @teod,
in the example config file you referenced to, the only two directories which are stored in the cache are `~/.turtle` and `~/yarn_cache`. However, neither of them should contain `app.json`, it should be in your project directory, so I don't understand the problem you're having. Could you please describe it better?

**Comment by teod** [comment]
Hi @dsokal , my issue is that using the example config it keeps building with the same `expo.ios.buildNumber` and `expo.android.versionCode`, even though I update these values between the builds. Thanks !

**Comment by dsokal** [comment]
That's interesting, are you completely sure you're doing it right? I still don't know how it could be related in any way to the way we cache Turtle dependencies.

**Comment by teod** [comment]
Yes I do, that's really weird somehow it has something to do with circle ci executors, I'll investigate more. Thanks !

**Comment by teod** [comment]
I think I'm gonna close this issue, since I'm not sure if it's related to turtle, will reopen if contrary.
