### ISSUE TITLE
v0.12.8: error parsing option. Command is "turtle sa"

### ISSUE THREAD

**Issue by borgogelli** [expo/turtle#160]
Turtle v0.12.8 installed.

`turtle setup:android`
print out the right message
`platform: "android"`

While
`turtle sa `
print out a wrong message
`platform: "ios"`

instead I would expected to read
`platform: "android"`

**Comment by dsokal** [comment]
This should be fixed in the upcoming release (https://github.com/expo/turtle/commit/8615f2eb9b7688cb5941b79dbe46c08fd187931b). Sorry that it took us so long.
