### ISSUE TITLE
Node 13

### ISSUE THREAD

**Issue by Ghostylnx** [expo/turtle#164]
### Question Checklist

- [x] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [x] I read [docs.expo.io](https://docs.expo.io) (Managed Workflow > Distributing Your App).
- [x] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).

### Question Subject
Node 13 support for turtle

#### Question Description
When installing turtle with node 13 it won't install because sharp 0.22.1 doesn't support node 13.
Will there be official node 13 support for turtle?

**Comment by peisenmann** [comment]
I realize that Node 12 is LTS and the Turtle CLI is primarily intended for CI setups, but I'd like to use this locally and rolling back to Node 12 isn't an option. Any support for this would be great.

**Comment by brentvatne** [comment]
it looks like we need to update to sharp 0.23.x cc @dsokal
