### ISSUE TITLE
Android build fail with SDK36 

### ISSUE THREAD

**Issue by outaTiME** [expo/turtle#166]
Today i try to make build with the new sdk and fails on Android, iOS works as expected. 

Here the exception, any advices, thanks !!!

```
BUILD SUCCESSFUL in 6m 47s
32 actionable tasks: 32 executed
Error: ENOENT: no such file or directory, lstat '/app/turtle/workingdir/android/sdk36/android-shell-app/app/build/outputs/bundle/release/app.aab'
```

Forum reference:

https://forums.expo.io/t/android-build-fail-with-sdk36/30980?u=outatime

**Comment by dsokal** [comment]
Hey @outaTiME,
thanks for reporting! Could you please try running a build again? It should be fixed now. Sorry for the inconvenience.

**Comment by outaTiME** [comment]
It working right now @dsokal, thanks !!!
