### ISSUE TITLE
Expo (turtle-cli): build fails when using a wildcard provisioning profile

### ISSUE THREAD

**Issue by tasn** [expo/turtle#168]
As you can see, the code in this function doesn't take into account wildcard provisioning profiles.

https://github.com/expo/expo-cli/blob/4c4b6166c396fc803163534c38fe5dc130271f81/packages/xdl/src/detach/IosCodeSigning.js#L57

It should be very easy to fix assuming this is the only issue related to wildcard certs.

**Comment by dsokal** [comment]
Hi @tasn,
you should be able to build an app with a wildcard provisioning profile now :) Just remember to upload the profile manually with `expo-cli`. We don't support (and we will never) generating such profiles.

**Comment by tasn** [comment]
@dsokal, thanks a lot! As for uploading to `expo`: that won't be necessary for me, as I'm using `turtle` to build my app instead of expo.
