### ISSUE TITLE
Add config flag

### ISSUE THREAD

**Issue by teod** [expo/turtle#17]
Is it possible to have the --config flag to specify a different app.json same way expo build --config flag works ?
https://forums.expo.io/t/building-with-alternate-app-json-files/10690/4

**Comment by dsokal** [comment]
And what is your case?

**Comment by teod** [comment]
I am building whitelabeled apps, they are using the same codebase, so the build should run from the same directory, I am using release channels for differences between the apps on code level, and different app.json files for setting the app settings and assets (icons, splash...) differently. The only drawback right now is that I can't set the config as a command line parameter same as expo publish and expo build.

**Comment by dsokal** [comment]
`--config` parameter will be added in the next release.
