### ISSUE TITLE
wrong certificate in Google Console when i build with turtle

### ISSUE THREAD

**Issue by Menogus** [expo/turtle#174]
i use expo build for google play console - and expo build normal version with certificates for GP console
start: 
`expo build:android --clear-credentials`
then i got **upload.pem:** 
`expo fetch:android:upload-cert`
then i got **output.zip**: 
`java -jar pepk.jar --keystore=KEYSTORE.jks --alias=KEYSTORE_ALIAS --output=output.zip --encryptionkey=eb10fe8f7c7c9df715022017b00c6471f8ba8170b13049a11e6c09ffe3056a104a3bbe4ac5a955f4ba4fe93fc8cef27558a3eb9d2a529a2092761fb833b656cd48b9de6a --include-cert`

then i upload **output.zip** and **upload.pem** to GP console and after that i can upload APK/BUNDLE in GP Console....

but when i try build with turtle like:

`turtle build:android -t app-bundle -c app.json --keystore-path KEYSTORE.jks --keystore-alias KEYSTORE_ALIAS `

and try upload apk/bundle to GP Console - it's error because wrong certificate

what i need to do?

**Comment by wkozyra95** [comment]
resolved on forum
https://forums.expo.io/t/wrong-certificate-in-google-console-when-i-build-with-turtle/32488
