### ISSUE TITLE
Can not install turtle-cli on mac os

### ISSUE THREAD

**Issue by sp0033212000** [expo/turtle#179]
### New Issue Checklist

I can't install turtle-cli on my mac os

##### Command executed
$ sudo npm install -g turtle-cli

##### Complete output when running turtle, including the stack trace and command used

<details>
  <pre> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 19.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/grpc
node-pre-gyp ERR! node -v v10.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/usr/local/lib/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/usr/local/lib/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.24.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.24.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liaojiwei/.npm/_logs/2020-02-07T06_45_35_958Z-debug.log </pre>
</details>

### Environment

<details>
  <pre> Expo CLI 3.11.5 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.12.0 - /usr/local/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.11.5 </pre>
</details>

**Comment by dsokal** [comment]
The recommended way of installing turtle-cli is to install it as a non-root user (= without sudo). Try doing so and let me know if the problem goes away. If you can't install global packages without sudo then I'd recommend using nvm.

**Comment by sp0033212000** [comment]
> The recommended way of installing turtle-cli is to install it as a non-root user (= without sudo). Try doing so and let me know if the problem goes away. If you can't install global packages without sudo then I'd recommend using nvm.

It work! I solved the problem by nvm, thanks!

**Comment by rehmankhalil1001** [comment]
@sp0033212000 can you guide me on how to use nvm, i installed it using : [](https://itnext.io/nvm-the-easiest-way-to-switch-node-js-environments-on-your-machine-in-a-flash-17babb7d5f1b).

But i am not sure how to use it to install turtle CLI. The npm install -g turtle-cli command fails with the following error:


`
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.22.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2020-03-20T15_56_34_627Z-debug.log`



I am using Macos Catalina, version 10.15.3.

Thank you in advance :)

**Comment by Jozott00** [comment]
For me it fails with:

`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.24.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.24.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jozott/.npm/_logs/2020-03-31T19_59_46_353Z-debug.log`

MacOS Catalina, version 10.15.3

**Comment by brentvatne** [comment]
https://github.com/grpc/grpc-node/issues/1183

**Comment by Jozott00** [comment]
@brentvatne Unfortunately none of the solutions described in the thread worked for me :/ 
Only when I unintentionally installed turtle-cli within the React Native Project, without -g, did the installation go through. Of course, the package is not globally useless.

**Comment by rehmankhalil1001** [comment]
@Jozott00 as mentioned above by @dsokal, it works using NVM.
what i did:

1. Understood how NVM works(never used it before)
2. Installed and Used node version 12.0.0
3. Globally installed turtle-cli and used 
4. Builds APK and AAB 

Unfortunately when i install it on simulator or real device, my react native APK build does not seem to work and i had to go back to using the expo build command.

**Comment by Jozott00** [comment]
@rehmankhalil1001  wow ok thank you very much! I already tried it with a `12.x` and a `10.x `version, both didn't work. For some reason it did with the `12.0.0` version of node
