### ISSUE TITLE
Add "Average Wait Time" indicator to the left-hand side of the interface.

### ISSUE THREAD

**Issue by Akuma-U1** [expo/turtle#183]
### Feature Request
Hi,
I think it would be quite useful to put an "average waiting time" below the indicators for "iOS" and "Android" on the left-hand side of the turtle interface. 
#### Motivation Behind Feature

This would make it easier to see how long you can expect your build for a specific platform to take without having to hover over the  "_waiting + processing / processing time (in minutes)_" graph.

![image](https://user-images.githubusercontent.com/33059719/75367901-afd71280-58c9-11ea-8390-5f6c6463b33b.png)

#### Alternatives or Workarounds
Currently the best way to do this is by trying to hover your mouse over the graph titled _"waiting + processing / processing time (in minutes)"_ for Android, or _"iOS archive builds - total / processing time (in minutes)"_ for iOS.

![image](https://user-images.githubusercontent.com/33059719/75368077-df861a80-58c9-11ea-80d1-94255df199a0.png)

**Comment by dsokal** [comment]
<img width="534" alt="Screenshot 2020-07-15 at 13 17 18" src="https://user-images.githubusercontent.com/5256730/87539065-92022280-c69d-11ea-8aea-3c7f1067e348.png">
I just added these - the dashboard should be more useful now.
