### ISSUE TITLE
Issue building an APK standalone

### ISSUE THREAD

**Issue by ryanfox1985** [expo/turtle#184]
### Question Checklist

- [X] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [X] I read [docs.expo.io](https://docs.expo.io) (Managed Workflow > Distributing Your App).
- [X] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).

### Question

Recently I have configured a continuous integration process to build the standalone APK like this:
```sh
yarn turtle setup:android # inside the docker image
/usr/local/bin/turtle build:android -u $EXPO_USER -p $EXPO_PASSWORD --keystore-path ./ci.keystore --keystore-alias business -t apk -o ./builds/master.apk
```

And the process is working and building the APK in the output, however, when I install the the application is weird, the new release doesn't have the latest changes is like is building the APK using a cache.

Also I have another question is it possible to run the command without an Expo Account?

Thanks!

**Comment by dsokal** [comment]
Hi!
1. turtle-cli doesn't publish your app so you need to run `expo publish` before. This is why it seems cached.
2. Yes, it is possible to run the command without an Expo Account but you need to self-host your app - https://docs.expo.io/versions/v36.0.0/distribution/hosting-your-app/

**Comment by ryanfox1985** [comment]
Hi @dsokal thanks for the quick answer. I added these previous lines:

```sh
yarn expo login -u $EXPO_USER -p $EXPO_PASSWORD --non-interactive
yarn expo publish
yarn turtle setup:android # inside the docker image
/usr/local/bin/turtle build:android -u $EXPO_USER -p $EXPO_PASSWORD --keystore-path ./ci.keystore --keystore-alias business -t apk -o ./builds/master.apk
```

And the problem stills, the apk doesn't have the latest version.
