### ISSUE TITLE
[iOS] Bundle Action Extension with container app

### ISSUE THREAD

**Issue by giuseppeg** [expo/turtle#185]
### Question Checklist

- [x] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [x] I read [docs.expo.io](https://docs.expo.io) (Managed Workflow > Distributing Your App).
- [x] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).

### Question Subject

Bundle an Action Extension when turtle builds an ejected (but not modified) Expo app

#### Question Description

Thanks for building turtle CLI - it is phenomenal!

I am building an app with Expo CLI and I would like to add a simple Action Extension in iOS. 

I am trying to do so at build time by ejecting to bare on the fly and adding the Action Extension. I am adding the Action Extension by opening `ios/MyProject.xcworkspace` in xcode and adding a target to MyProject. I can successfully run the app in the simulator with `yarn ios` (`react-native run-ios`).

I am then building the application locally with turtle CLI, successfully. As I am not making any fundamental change to my app turtle is able to build the application for both app store and simulator but the Action Extension is not bundled.  

**My question would be**, can you suggest a way to patch turtle CLI so that it can pick up and bundle the Action Extension with the main container app? I'd be happy to contribute back to the project or with a guide once I have managed to make it work for my small app - it seems a feature that many want/need :)

Thank you in advance for your help!

**Comment by dsokal** [comment]
Hello @giuseppeg,

the thing you want to achieve is not really a straightforward task. This is not because of the complexity of your change but rather because of the design of Turtle CLI. Turtle CLI doesn't compile the Xcode project that appears in your Expo project after ejecting. Turtle CLI, when installed from npm, comes bundled with URLs to "shell apps". A shell app is a precompiled native project. As for iOS, it is a precompiled Xcode project. Turtle CLI only modifies a few configuration files, packs the app into an IPA archive and signs the file with a distribution certificate and the provisioning profile.
This design makes you create your own shell app if you wish to make any change to the Xcode project.  What's even worse (for you) is that each SDK version has its own shell app. If you ever decided to build your shell app you'd need to build it again for each Expo SDK upgrade.

How to build your own shell app?
- clone the [expo/expo](https://github.com/expo/expo) repo
- follow https://github.com/expo/expo/blob/master/CONTRIBUTING.md#-download-and-setup
- check out the `shell_app_ios_build` job that we run on CircleCI -https://github.com/expo/expo/blob/master/.circleci/config.yml#L649
- run all the commands from the CircleCI job to build the shell app
- (optional) the name of the job for Android is `shell_app_android_build `

Unfortunately, I think I can't be of any more help. At the moment we don't support building apps with modifications in the native code. Because of that, I'm closing the issue, sorry :(

**Comment by giuseppeg** [comment]
@dsokal thank you for the speedy reply and for clarifying on this! Your explanation was super helpful :) 
How would you instruct Turtle CLI to pick my custom shell in case?

**Comment by dsokal** [comment]
Oh, sorry for not covering this:
- edit the file for you SDK version in this directory - https://github.com/expo/turtle/tree/master/shellTarballs/ios
- either publish turtle-cli to npm under your own name or run https://github.com/expo/turtle/blob/master/bin/turtle.js from the repository (I use a shell alias for local development, like this - `alias turtle_dev=/Users/dsokal/workspace/expo/turtle/bin/turtle.js`)

**Comment by giuseppeg** [comment]
Awesome thank you a lot!

**Comment by giuseppeg** [comment]
hi @dsokal sorry to bother you again. I tried your suggestion and I was able to build an app shell successfully. I added the action extension to the built shell before creating the final archive. I then build my Expo app with TurtleCLI using my custom app shell but the action extension doesn't show up in Safari yet. Do you have any idea why? I basically added a new target to `shellAppWorkspaces/default/ios/ExpoKitApp.xcworkspace/`

**Comment by dsokal** [comment]
Hi, 
have you uploaded the shell app anywhere and changed the link in https://github.com/expo/turtle/tree/master/shellTarballs/ios ?

**Comment by giuseppeg** [comment]
@dsokal I patched Turtle CLI to pick it up from the local FS. The manual build produces the following folders:

* exponent-view-template 
* shellAppBase-builds 
* shellAppWorkspaces 
* ios

https://github.com/expo/expo/blob/958d95ffc975ca66139635680149875192f5237d/.circleci/config.yml#L686-L693

Do you have any idea where or when I should patch the base shell app to add the action extension? Should I patch the built shell before creating the archive or before even building the shell app? It'd be great if you could point me to the exact xcode project to patch :) 

Thanks a lot for taking the time to read my "out of scope" questions! I'd likely write about all of this once I am done.

**Comment by dsokal** [comment]
I think you should patch the ios app before building the shell app.
The ios app is placed here https://github.com/expo/expo/tree/sdk-36/ios Please note that it's on the `sdk-36` branch. Normally, each SDK version has its own branch from where we build the shell app. If you wish to patch another SDK version then just simply change the branch to `sdk-VERSION`.

**Comment by giuseppeg** [comment]
Hi @dsokal sorry to bother you again.

I am trying to build the Expo 37.0.0 app shell (for the simulator at the moment) and I get the following error:

```shell
▸ Running script 'Prepare Expo'
    no rule to process file '~/code/projs/expo/template-files/keys.json' of type 'text.json' for architecture 'i386' (in target 'ExpoKit' from project 'Pods')
    no rule to process file '~/code/projs/expo/template-files/keys.json' of type 'text.json' for architecture 'x86_64' (in target 'ExpoKit' from project 'Pods')
** BUILD FAILED **


The following build commands failed:
  PhaseScriptExecution Prepare\ Expo ~/code/projs/expo/shellAppBase-simulator/Build/Intermediates.noindex/ExpoKitApp.build/Release-iphonesimulator/ExpoKitApp.build/Script-B5722AD01DFB7E3F0084848F.sh
(1 failure)
[11:25:27] 'ios-shell-app' errored after 6.43 min
[11:25:27] Error: set -o pipefail && xcodebuild -workspace ExpoKitApp.xcworkspace -scheme ExpoKitApp -configuration Release -derivedDataPath ../../../shellAppBase-simulator -UseModernBuildSystem=YES -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ARCHS="i386 x86_64" ONLY_ACTIVE_ARCH=NO | xcpretty exited with non-zero code: 65
    at ChildProcess.completionListener (~/code/projs/expo/tools-public/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:466:23)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
    ...
    at spawnAsync (~/code/projs/expo/tools-public/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnAsyncThrowError (/@expo/xdl@57.8.6/src/detach/ExponentTools.ts:132:19)
    at _buildAsync (/@expo/xdl@57.8.6/src/detach/IosShellApp.js:129:9)
    at Object.buildAndCopyArtifactAsync (/@expo/xdl@57.8.6/src/detach/IosShellApp.js:353:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
Unfortunately the error message doesn't give any obvious pointer to me (I am a noob).

For some reason I was able to build 36.0.0 just fine before I cloned this repo again and started fresh to build 37.0.0 with

```shell
sdk-37  $ gulp ios-shell-app --action build --type simulator --verbose true --skipRepoUpdate --shellAppSdkVersion 37.0.0
```

Do you have any idea of what's going on by any chance? Thank you in advance!

**Comment by jpstrikesback** [comment]
hey @giuseppeg just wondering if you ever figured this out for sdk 37 (and perhaps beyond)?

Cheers!

**Comment by giuseppeg** [comment]
@jpstrikesback unfortunately not - I gave up due to lack of time.

**Comment by jpstrikesback** [comment]
@giuseppeg thanks for the response!
