### ISSUE TITLE
Android build fail when fetching config from the python server serving the dist folder.

### ISSUE THREAD

**Issue by BBenGit** [expo/turtle#187]
### New Issue Checklist

- [x] Updated turtle-cli to the latest version (`yarn global add turtle-cli` or `npm install --global turtle-cli`).
- [x] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [x] I read [docs.expo.io](https://docs.expo.io) (Managed Workflow > Distributing Your App).
- [x] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).
- [x] **I enclosed the complete output when running turtle, including the stack trace and command used.**

### Issue Description

Android build fail when fetching config from the python server serving the dist folder.

I have managed to build the app once before without issues. I followed the guide with `expo export ` and expo 

python command  in dist folder : `python -m http.server -b 127.0.0.1`

Server runs no problem.
![image](https://user-images.githubusercontent.com/44926723/75874097-5a42be80-5e11-11ea-91b2-bd0db617ca3e.png)

But when I run the turtle build command i got this :
```
127.0.0.1 - - [04/Mar/2020 12:07:39] code 400, message Bad request version ("Á>$x=\x95&]?Ö\x00v\x13\x02\x13\x03\x13\x01À/À+À0À,\x00\x9eÀ'\x00gÀ(\x00k\x00£\x00\x9fÌ©Ì¨ÌªÀ¯À\xadÀ£À\x9fÀ]ÀaÀWÀS\x00¢À®À¬À¢À\x9eÀ\\À`ÀVÀRÀ$\x00jÀ#\x00@À")
127.0.0.1 - - [04/Mar/2020 12:07:39] "TPW°ÐãÑ¬/¨ï;ê²or¿|çhXÅ%CXxùÏ 'Ý¼ïob4.7¡ïÃïCÚ Á>$x=&]?ÖvÀ/À+À0À,À'gÀ(k£Ì©Ì¨ÌªÀ¯À­À£ÀÀ]ÀaÀWÀS¢À®À¬À¢ÀÀ\À`ÀVÀRÀ$jÀ#@À" 400 -
```

##### Command executed

`
turtle build:android`

##### Complete output when running turtle, including the stack trace and command used

<details>
  <pre>EXPO_ANDROID_KEYSTORE_PASSWORD="================" \                                                                                                                          1 ↵  12:05:03
EXPO_ANDROID_KEY_PASSWORD="================" \
turtle build:android \
  --type apk \
  --keystore-path ./keystore.jks \
  --keystore-alias "graphcar-alias" \
  --public-url http://127.0.0.1:8000/android-index.json
Mar 4 12:07:37 turtle[14367] INFO:  Using manifest: {"name":"graphcar","slug":"graphcar","privacy":"public","sdkVersion":"36.0.0","platforms":["ios","android","web"],"version":"1.0.3","orientation":"portrait","icon":"./assets/icon.png","splash":{"image":"./assets/splash.png","resizeMode":"contain","backgroundColor":"#ffffff","imageUrl":"https://127.0.0.1:8000/assets/932faf8ba660f7818d589d17a605ac6f"},"updates":{"fallbackToCacheTimeout":0},"ios":{"supportsTablet":true},"android":{"package":"com.independant.graphcar"},"locales":{},"iconUrl":"https://127.0.0.1:8000/assets/f284e2c14f2f1ce2a1856a93ed0def6e","bundledAssets":["asset_3a2ba31570920eeb9b1d217cabe58315.ttf","asset_8b12b3e16d591abc926165fa8f760e3b.json","asset_744ce60078c17d86006dd0edabcd59a7.ttf","asset_461d9bba8b6a3c91675039df12cfe6ca.json","asset_140c53a7643ea949007aa9a282153849.ttf","asset_94c4ffdcbffeb0570c635d7f8edd8a25.json","asset_6beba7e6834963f7f171d3bdd075c915.ttf","asset_648f2d510967a87880abfed9476aeb28.json","asset_b06871f281fee6b241d60582ae9369b9.ttf","asset_f1f91feb805137c9283fb766620ec5eb.json","asset_09dd345dbd4ec5a0874841d5749ac153.json","asset_0886a6b127c6057cee83f9c65c7ffd62.json","asset_2e562d4ebf15395f00bc738738f79291.ttf","asset_872545dde71de3842234bf6afe80c4cb.ttf","asset_c6aef942e3668158ec29d4adcb2e768f.ttf","asset_e20945d7c929279ef7a6f1db184a4470.ttf","asset_60668d999bbaf663420340f7bdd580d7.json","asset_b2e0fc821c6886fb3940f85a3320003e.ttf","asset_3e6805fbc794680014716b8c752f20b8.json","asset_5a293a273bee8d740a045d9922b9a9ae.ttf","asset_b582e1c8a605c3b9a1c26e09789a78d4.json","asset_a37b0c01c0baf1888ca812cc0508f6e2.ttf","asset_7e078700f0c35367a56c5bbb2047dda7.json","asset_8e7f807ef943bff1f6d3c2c6e0f3769e.ttf","asset_fdc01171a7a7ea76b187afcd162dee7d.json","asset_d2285965fe34b05465047401b8595dd0.ttf","asset_647543ebfccf6e5495434383598453d1.json","asset_5cdf883b18a5651a29a4d1ef276d2457.ttf","asset_74d124a3caeac2bea111f3ca2f2dd34a.json","asset_004c2bbb035d8d06bb830efc4673c886.png","asset_2327736b3ea09c41abfb69be1221f430.png","asset_51671417ef20e0bbc32f0a2bc6edfa95.png","asset_a7b9dc9de5f8f1fb1afbef917619a5ac.png","asset_4bdd6aad790c6c8370a06876ec7d31e1.png","asset_4b9cf0cc747e3c1abc541befa05b1e37.png","asset_4d882c2509eaa724d486f6dac753b8f5.json","asset_85ae102ad9b323d315f4810f81d12952.json","asset_e1e771bac050d06a83d3adf2a50029d8.json","asset_f2f34dc3f2f079791cb5f45c01e81064.json","asset_46c8473e3a6dc096e844e4de60b8e01f.json","asset_2ac32dec71143dccca808a592a85eb9f.json","asset_59e1d07580be5bc3c66af78930b04b98.json","asset_1edd5017f455b09c608e175b1285c06d.png"],"assetUrlOverride":"./assets","publishedTime":"2020-03-04T11:00:49.479Z","commitTime":"2020-03-04T11:00:49.479Z","revisionId":"8O1NWeZb2y","id":"@foofoon/graphcar","bundleUrl":"https://127.0.0.1:8000/bundles/android-7d0832b7680425e01a29d593c6dad315.js","platform":"android","dependencies":["expo","moment","native-base","prop-types","react","react-dom","react-native","react-native-datepicker","react-native-elements","react-native-fab","react-native-gesture-handler","react-native-modal","react-native-navigation","react-native-reanimated","react-native-svg","react-native-svg-charts","react-native-tab-view","react-native-web","react-redux","redux","redux-persist"]}
  platform: "android"
  buildPhase: "reading manifest"
Mar 4 12:07:37 turtle[14367] INFO:  Starting build process
  platform: "android"
  buildPhase: "starting builder"
Mar 4 12:07:37 turtle[14367] INFO:  ImageUtils: setting image functions to alternative sharp implementations
  platform: "android"
  buildPhase: "icons setup"
Mar 4 12:07:37 turtle[14367] INFO:  Resolving universal modules dependencies
  platform: "android"
  buildPhase: "resolve native modules"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-ads-admob:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding @unimodules/core:5.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-ads-facebook:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-analytics-amplitude:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-analytics-segment:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding unimodules-constants-interface:5.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-app-auth:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-app-loader-provider:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-apple-authentication:2.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding @unimodules/react-native-adapter:5.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding unimodules-font-interface:5.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding unimodules-image-loader-interface:5.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding unimodules-permissions-interface:5.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-application:2.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-av:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-background-fetch:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-task-manager:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding unimodules-task-manager-interface:5.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-barcode-scanner:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding unimodules-barcode-scanner-interface:5.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-battery:2.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-bluetooth:1.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-blur:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-brightness:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-calendar:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-camera:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding unimodules-camera-interface:5.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding unimodules-file-system-interface:5.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding unimodules-face-detector-interface:5.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-cellular:2.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-constants:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-contacts:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-crypto:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-device:2.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-document-picker:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-error-recovery:1.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-face-detector:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-facebook:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-file-system:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-font:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-gl:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-gl-cpp:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-google-sign-in:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-haptics:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-image-manipulator:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-image-picker:8.0.2
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-permissions:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-in-app-purchases:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-intent-launcher:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-keep-awake:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-linear-gradient:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-local-authentication:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-localization:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-location:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-mail-composer:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-media-library:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-network:2.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-payments-stripe:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-print:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-random:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-secure-store:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-sensors:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding unimodules-sensors-interface:5.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-sharing:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-sms:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-speech:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-sqlite:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-store-review:2.0.1
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-updates:0.0.1-rc.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-video-thumbnails:4.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Adding expo-web-browser:8.0.0
  platform: "android"
Mar 4 12:07:37 turtle[14367] INFO:  Using manifest: {"name":"graphcar","slug":"graphcar","privacy":"public","sdkVersion":"36.0.0","platforms":["ios","android","web"],"version":"1.0.3","orientation":"portrait","icon":"./assets/icon.png","splash":{"image":"./assets/splash.png","resizeMode":"contain","backgroundColor":"#ffffff","imageUrl":"https://127.0.0.1:8000/assets/932faf8ba660f7818d589d17a605ac6f"},"updates":{"fallbackToCacheTimeout":0},"ios":{"supportsTablet":true},"android":{"package":"com.independant.graphcar"},"locales":{},"iconUrl":"https://127.0.0.1:8000/assets/f284e2c14f2f1ce2a1856a93ed0def6e","bundledAssets":["asset_3a2ba31570920eeb9b1d217cabe58315.ttf","asset_8b12b3e16d591abc926165fa8f760e3b.json","asset_744ce60078c17d86006dd0edabcd59a7.ttf","asset_461d9bba8b6a3c91675039df12cfe6ca.json","asset_140c53a7643ea949007aa9a282153849.ttf","asset_94c4ffdcbffeb0570c635d7f8edd8a25.json","asset_6beba7e6834963f7f171d3bdd075c915.ttf","asset_648f2d510967a87880abfed9476aeb28.json","asset_b06871f281fee6b241d60582ae9369b9.ttf","asset_f1f91feb805137c9283fb766620ec5eb.json","asset_09dd345dbd4ec5a0874841d5749ac153.json","asset_0886a6b127c6057cee83f9c65c7ffd62.json","asset_2e562d4ebf15395f00bc738738f79291.ttf","asset_872545dde71de3842234bf6afe80c4cb.ttf","asset_c6aef942e3668158ec29d4adcb2e768f.ttf","asset_e20945d7c929279ef7a6f1db184a4470.ttf","asset_60668d999bbaf663420340f7bdd580d7.json","asset_b2e0fc821c6886fb3940f85a3320003e.ttf","asset_3e6805fbc794680014716b8c752f20b8.json","asset_5a293a273bee8d740a045d9922b9a9ae.ttf","asset_b582e1c8a605c3b9a1c26e09789a78d4.json","asset_a37b0c01c0baf1888ca812cc0508f6e2.ttf","asset_7e078700f0c35367a56c5bbb2047dda7.json","asset_8e7f807ef943bff1f6d3c2c6e0f3769e.ttf","asset_fdc01171a7a7ea76b187afcd162dee7d.json","asset_d2285965fe34b05465047401b8595dd0.ttf","asset_647543ebfccf6e5495434383598453d1.json","asset_5cdf883b18a5651a29a4d1ef276d2457.ttf","asset_74d124a3caeac2bea111f3ca2f2dd34a.json","asset_004c2bbb035d8d06bb830efc4673c886.png","asset_2327736b3ea09c41abfb69be1221f430.png","asset_51671417ef20e0bbc32f0a2bc6edfa95.png","asset_a7b9dc9de5f8f1fb1afbef917619a5ac.png","asset_4bdd6aad790c6c8370a06876ec7d31e1.png","asset_4b9cf0cc747e3c1abc541befa05b1e37.png","asset_4d882c2509eaa724d486f6dac753b8f5.json","asset_85ae102ad9b323d315f4810f81d12952.json","asset_e1e771bac050d06a83d3adf2a50029d8.json","asset_f2f34dc3f2f079791cb5f45c01e81064.json","asset_46c8473e3a6dc096e844e4de60b8e01f.json","asset_2ac32dec71143dccca808a592a85eb9f.json","asset_59e1d07580be5bc3c66af78930b04b98.json","asset_1edd5017f455b09c608e175b1285c06d.png"],"assetUrlOverride":"./assets","publishedTime":"2020-03-04T11:00:49.479Z","commitTime":"2020-03-04T11:00:49.479Z","revisionId":"8O1NWeZb2y","id":"@foofoon/graphcar","bundleUrl":"https://127.0.0.1:8000/bundles/android-7d0832b7680425e01a29d593c6dad315.js","platform":"android","dependencies":["expo","moment","native-base","prop-types","react","react-dom","react-native","react-native-datepicker","react-native-elements","react-native-fab","react-native-gesture-handler","react-native-modal","react-native-navigation","react-native-reanimated","react-native-svg","react-native-svg-charts","react-native-tab-view","react-native-web","react-redux","redux","redux-persist"]}
  platform: "android"
  buildPhase: "reading manifest"
Mar 4 12:07:37 turtle[14367] INFO:  ~/.turtle/workingdir/android/sdk36/tools-public ~/.turtle/workingdir/android/sdk36/android/app
  platform: "android"
  buildPhase: "confirming that dynamic macros exist"
  source: "stdout"
Mar 4 12:07:37 turtle[14367] INFO:  ~/.turtle/workingdir/android/sdk36/android/app
  platform: "android"
  buildPhase: "confirming that dynamic macros exist"
  source: "stdout"
Mar 4 12:07:39 turtle[14367] ERROR: Error: write EPROTO 4428545472:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
  platform: "android"
Mar 4 12:07:39 turtle[14367] ERROR: Failed to build standalone app
  err: Error: write EPROTO 4428545472:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

      at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
  platform: "android" </pre>
</details>

### Environment

<details>
  <pre> Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
    npmGlobalPackages:
      expo-cli: 3.13.1 </pre>
</details>

**Comment by dsokal** [comment]
Hi!
How did you manage to export your app with non-https `--public-url`?

This is the error you should have seen:
```
expo export --public-url http://localhost:2137
--public-url must be a valid HTTPS URL.
```

It looks like you've exported your app using one URL and your passing another to turtle-cli.
