### ISSUE TITLE
Say which version of Java is found if it's incorrect 

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [expo/turtle#191]
### Feature Request
Following #190, this was a little frustrating to see:

```
% turtle setup:android
Mar 9 11:12:41 turtle[65155] ERROR: Please install JDK (version 8) - check https://jdk.java.net/
  err: Error: You're using a wrong Java version, please install version 8
```

#### Motivation Behind Feature
It would have been easier to figure out that JDK 13 is, in fact, not supported, if it was clear that `turtle-cli` was picking up the version correctly. I was surprised at the big version gap.

#### Feature Description
In the check for `javac` version, can we add a "your version is XYZ" string?

#### Alternatives or Workarounds
I console logged in `build/bin/setup/android/index.js` 😄:

```
% turtle setup:android
{
  stderr: 'java version "13.0.2" 2020-01-14\nJava(TM) SE Runtime ' +
    'Environment (build 13.0.2+8)\nJava HotSpot(TM) 64-Bit ' +
    'Server VM (build 13.0.2+8, mixed mode, sharing)\n',
  matchResult: [
    'java version "13.0.2"',
    '0',
    index: 0,
    input: 'java version "13.0.2" 2020-01-14\nJava(TM) SE Runtime ' +
      'Environment (build 13.0.2+8)\nJava HotSpot(TM) 64-Bit ' +
      'Server VM (build 13.0.2+8, mixed mode, sharing)\n',
    groups: undefined
  ]
}
Mar 9 11:22:46 turtle[65676] ERROR: Please install JDK (version 8) - check https://jdk.java.net/
  err: Error: You're using a wrong Java version, please install version 8
```

**Comment by dsokal** [comment]
Hi @JoshuaKGoldberg,
This is a great idea! I'll change the error message soon to make it more meaningful.

**Comment by dsokal** [comment]
This is fixed in https://github.com/expo/turtle/commit/941a605591ded83e70a6db8033d052c5291abc77
The fix will be included in the upcoming version of turtle-cli.
