### ISSUE TITLE
JS assets are often not updated for subsequent Android apk builds

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [expo/turtle#193]
### New Issue Checklist

- [x] Updated turtle-cli to the latest version (`yarn global add turtle-cli` or `npm install --global turtle-cli`).
- [x] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [x] I read [docs.expo.io](https://docs.expo.io) (Managed Workflow > Distributing Your App).
- [x] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).
- [x] **I enclosed the complete output when running turtle, including the stack trace and command used.**

### Issue Description
Approximate repro steps:

1. Add `console.log("first")` to a React component's `render()`
2. Build an apk using `expo build:android`
3. Run that apk using an AVD emulator locally -> the `"first"` log shows up in `react-native log-android` ✅ 
4. Update the component to say `console.log("second")`
5. Build an apk using `turtle` 
6. Run that new apk using an AVD emulator locally -> the `"second"` log correctly shows up in `react-native log-android` ✅ 
7. Update the component to say `console.log("third")`
8. Build an apk using `turtle` 
9. Run that new apk using an AVD emulator locally -> the `"second"` log _still_ shows up in `react-native log-android` ❌ 

Some notes:

  * If you repeat steps 1-3 with different log messages, they're consistently updated
  * At the beginning of steps 6 and 9, Android Studio does mention that there's already an application with the same package but a different signature in a prompt offering to uninstall the existing application. This issue shows up regardless of whether you uninstall the app from your emulator first or through that prompt.

##### Command executed

```
turtle build:android --release-channel default -t apk
```

##### Complete output when running turtle, including the stack trace and command used

Too many logs for an issue.
https://gist.github.com/JoshuaKGoldberg/340b77cd28b540dfea1069bb06a0fbc2

### Environment

<details>
  <pre>   Expo CLI 3.13.2 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.2 => 36.0.2 
      react: 16.12.0 => 16.12.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.13.2
 </pre>
</details>

**Comment by dsokal** [comment]
Hello @JoshuaKGoldberg!

I can exactly explain what's happening here:
- `expo build:android` published your JS code (including the React component with console.log) to Expo servers
- `turtle build:android` does **not** publish the JS code to Expo servers so the new apk still uses the previously generated bundle. 

I don't know why you saw the `"second"` log in the console after rebuilding the app with turtle-cli. You most probably either published the app with `expo publish` or built it with `expo build:(android|ios)` (publish is one of the steps unless you pass `--no-publish` flag).

Unfortunately, this is not an issue. Please see docs - https://docs.expo.io/versions/v36.0.0/distribution/turtle-cli/#publish-your-project
