### ISSUE TITLE
Failed to build standalone app

### ISSUE THREAD

**Issue by sgnd** [expo/turtle#196]
### New Issue Checklist
- [x] Updated turtle-cli to the latest version (`yarn global add turtle-cli` or `npm install --global turtle-cli`).
- [ ] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [x] I read [docs.expo.io](https://docs.expo.io) (Managed Workflow > Distributing Your App).
- [x] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).
- [x] **I enclosed the complete output when running turtle, including the stack trace and command used.**

### Issue Description
I'm already set environment variable on my OS user. 
```
export EXPO_USERNAME=mejik
export EXPO_PASSWORD=XgbsR4BT3***
export EXPO_ANDROID_KEYSTORE_PASSWORD=59ddf270a1604e0***
export EXPO_ANDROID_KEY_PASSWORD=46cc33b2bb734e1f9***
```

##### Command executed
If i run turtle with sudo like this:
```
sudo turtle build:android --keystore-path turtle-cli-example.jks --keystore-alias QHN1Z2FuZGEvdHVy*** -u mejik -p XgbsR4B***
```
##### Complete output when running turtle (with sudo)
<details>
  <pre> 
ERROR: Failed to build standalone app
  err: Error: Please provide all required credentials - Keystore (with password), Keystore alias and Key password
      at prepareCredentials (/usr/local/share/.config/yarn/global/node_modules/turtle-cli/src/bin/commands/build/android.ts:57:13)
      at /usr/local/share/.config/yarn/global/node_modules/turtle-cli/src/bin/utils/builder.ts:69:33
  platform: "android"
</pre>
</details>

If i run turtle without sudo like this:
```
turtle build:android --keystore-path turtle-cli-example.jks --keystore-alias QHN1Z2FuZGEvdHVy*** -u mejik -p XgbsR4B***
```
##### Complete output when running turtle (without sudo)
<details>
  <pre> 
Failed to build standalone app
  err: Error: Failed to log in with provided username and password
      at Object.ensureUserLoggedIn (/usr/local/share/.config/yarn/global/node_modules/turtle-cli/src/bin/utils/user.ts:20:13)
  platform: "android"
</pre>
</details>

### Environment

<details>
  <pre> Expo CLI 3.13.2 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 10.19.0 - /usr/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn
      npm: 6.13.4 - /usr/bin/npm
    npmPackages:
      expo: ~36.0.0 => 36.0.2
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 </pre>
</details>

**Comment by dsokal** [comment]
Hello @sgnd,

Thanks for reporting! Could you please tell me whether you have those `export`s in a .dotfile (.bashrc, .zshrc, etc.) or you run them just before executing `turtle build:android`?
Generally, the recommended way of running turtle-cli is to run it without sudo.
You're experiencing the issue because you most probably don't have those envs set in the console where you run turtle-cli. To verify whether the appropriate envs are set, just run `env` in your console and look for the names that supposed to be set.

**Comment by sgnd** [comment]
@dsokal Thank you for the reply.

But I already set env variables at `.bashrc` file, if I run `env` the output like this:
![image](https://user-images.githubusercontent.com/15070585/77146406-8ae75100-6abd-11ea-86d6-cdec181e5c46.png)

The problem always about authentication. Could you tell me to fix this, please?

**Comment by dsokal** [comment]
Are you sure your credentials are correct?
Try running: `expo logout && expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD` and let me know if you see "Success. You are now logged in as YOUR_USERNAME." in the output.

**Comment by sgnd** [comment]
I try it, the status is a success. I solved this problem, the problem because of permission in VPS. Thank you for helping me, you can close these issues.

**Comment by dsokal** [comment]
@hexdecimal16 what makes you think this is "the same issue"?
