### ISSUE TITLE
turtle setup:android failed no matter what i do

### ISSUE THREAD

**Issue by JudiPuak** [expo/turtle#199]
### New Issue Checklist

- [x] Updated turtle-cli to the latest version (`yarn global add turtle-cli` or `npm install --global turtle-cli`).
- [ ] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [x] I read [docs.expo.io](https://docs.expo.io) (Managed Workflow > Distributing Your App).
- [x] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).
- [x] **I enclosed the complete output when running turtle, including the stack trace and command used.**

### Issue Description
npm install -g turtle-cli --save
after completion, i ran turtle --version
gave error:  turtle-cli\node_modules\sharp\build\Release folder not found

npm install sharp
that command produced users\joe joe\node_modules\sharp\build\Release folder
i copied Release folder onto turtle-cli\node_modules\sharp\build

ran turtle --version
0.13.10

ran turtle setup:android --sdk-version 36.0.0
failed no matter what i did

please help
been learning react native using expo
my simple app runs smoothly using expo client in my samsung phone
now i want to produce the .apk

thank you so much

##### Command executed

turtle setup:android --sdk-version 36.0.0
##### Complete output when running turtle, including the stack trace and command used

<details>
  <pre> Joe Joe@Laptop MINGW32 ~
$ turtle setup:android --sdk-version 36.0.0
Mar 31 15:53:44 turtle[5108] INFO:  Downloading Android SDK
  platform: "android"
  buildPhase: "setting up environment"
Mar 31 16:08:39 turtle[5108] INFO:  Decompressing Android SDK
  platform: "android"
  buildPhase: "setting up environment"
Mar 31 16:09:22 turtle[5108] INFO:  Configuring Android SDK, this may take a while
  platform: "android"
  buildPhase: "setting up environment"
Mar 31 16:09:22 turtle[5108] INFO:  C:\Users\Joe Joe\AppData\Roaming\npm\node_modules\turtle-cli\scripts\android\configureAndroidSdk.sh: line 5: C:\Users\Joe: Is a directory
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Mar 31 16:09:22 turtle[5108] INFO:  C:\Users\Joe Joe\AppData\Roaming\npm\node_modules\turtle-cli\scripts\android\configureAndroidSdk.sh: line 14: C:\Users\Joe: Is a directory
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Mar 31 16:09:22 turtle[5108] INFO:  C:\Users\Joe Joe\AppData\Roaming\npm\node_modules\turtle-cli\scripts\android\configureAndroidSdk.sh: line 15: C:\Users\Joe: Is a directory
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Mar 31 16:09:22 turtle[5108] INFO:  C:\Users\Joe Joe\AppData\Roaming\npm\node_modules\turtle-cli\scripts\android\configureAndroidSdk.sh: line 16: C:\Users\Joe: Is a directory
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Mar 31 16:09:22 turtle[5108] INFO:  C:\Users\Joe Joe\AppData\Roaming\npm\node_modules\turtle-cli\scripts\android\configureAndroidSdk.sh: line 18: C:\Users\Joe: Is a directory
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Mar 31 16:09:22 turtle[5108] INFO:  C:\Users\Joe Joe\AppData\Roaming\npm\node_modules\turtle-cli\scripts\android\configureAndroidSdk.sh: line 22: C:\Users\Joe: Is a directory
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Mar 31 16:09:23 turtle[5108] ERROR: Failed to setup environment for android builds
  err: Error: ./configureAndroidSdk.sh exited with non-zero code: 1
      at ChildProcess.completionListener (.\AppData\Roaming\npm\node_modules\turtle-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:313:26)
      at ChildProcess.emit (events.js:223:5)
      at ChildProcess.EventEmitter.emit (domain.js:475:20)
      at ChildProcess.cp.emit (.\AppData\Roaming\npm\node_modules\turtle-cli\node_modules\cross-spawn\lib\enoent.js:34:29)
      at maybeClose (internal/child_process.js:1021:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
      ...
      at spawnAsync (.\AppData\Roaming\npm\node_modules\turtle-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:26:19)
      at Object.spawnAsyncThrowError (C:\@expo\xdl@57.4.0\src\detach\ExponentTools.ts:132:19)
      at _configureSdk (.\AppData\Roaming\npm\node_modules\turtle-cli\src\bin\setup\android\sdk.ts:54:23)
      at Object.ensureAndroidSDKIsPresent [as default] (.\AppData\Roaming\npm\node_modules\turtle-cli\src\bin\setup\android\sdk.ts:34:7)
      at prepareAndroidEnv (.\AppData\Roaming\npm\node_modules\turtle-cli\src\bin\setup\android\index.ts:67:21)
      at Object.setup [as default] (.\AppData\Roaming\npm\node_modules\turtle-cli\src\bin\setup\android\index.ts:55:3)
      at Object.setup [as default] (.\AppData\Roaming\npm\node_modules\turtle-cli\src\bin\setup\setup.ts:15:12)
      at setupAction (.\AppData\Roaming\npm\node_modules\turtle-cli\src\bin\commands\setup.ts:33:5)
      at .\AppData\Roaming\npm\node_modules\turtle-cli\src\bin\commands\setup.ts:22:40
      at Command.<anonymous> (.\AppData\Roaming\npm\node_modules\turtle-cli\src\bin\index.ts:23:12)
  platform: "android"</pre>
</details>

### Environment

can't run expo diagnostic
not an expo command 
windows 8.1 32-bit
have bash (git), node, expo, npm, java, turtle
versions can be seen in detail below
<details>
  <pre> Joe Joe@Laptop MINGW32 ~
$ bash -version
GNU bash, version 4.4.23(1)-release (i686-pc-msys)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Joe Joe@Laptop MINGW32 ~
$ node -v
v12.14.1

Joe Joe@Laptop MINGW32 ~
$ expo --version
3.13.1

Joe Joe@Laptop MINGW32 ~
$ npm -v
6.14.1

Joe Joe@Laptop MINGW32 ~
$ java -version
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) Client VM (build 25.241-b07, mixed mode)

Joe Joe@Laptop MINGW32 ~
$ turtle --version
0.13.10</pre>
</details>

**Comment by wkozyra95** [comment]
Hi
Turtle-cli is not supported on windows (only macOS and Linux).
