### ISSUE TITLE
Issue building android app bundle after upgrading to sdk 37

### ISSUE THREAD

**Issue by mlecoq** [expo/turtle#200]
### New Issue Checklist

- [x] Updated turtle-cli to the latest version (`yarn global add turtle-cli` or `npm install --global turtle-cli`).
- [x] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [x] I read [docs.expo.io](https://docs.expo.io) (Managed Workflow > Distributing Your App).
- [x] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).
- [x] **I enclosed the complete output when running turtle, including the stack trace and command used.**

### Issue Description

After upgrading to sdk 37, I cannot build anymore my android app.

I have updated my cli, tried to setup `turtle setup:android --sdk-version 37.0.0` and removed ~/.turtle/workingdir 

##### Command executed
turtle build:android --keystore-path ./my-upload-key.keystore --keystore-alias $EXPO_ANDROID_KEYSTORE_ALIAS --release-channel prod --type app-bundle -o ./build.aab

##### Complete output when running turtle, including the stack trace and command used

<details>
  <pre> Apr 1 11:40:40 turtle[23233] INFO:  ../../tools-public/check-dynamic-macros-android.sh: line 28: jq: command not found
  platform: "android"
  buildPhase: "confirming that dynamic macros exist"
  source: "stderr"
Apr 1 11:40:40 turtle[23233] ERROR: Error: ../../tools-public/check-dynamic-macros-android.sh exited with non-zero code: 127
    at ChildProcess.completionListener (/Users/mlecoq/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:311:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._h </pre>
</details>

### Environment

<details>
  <pre>
  Expo CLI 3.17.5 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.3 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
      react-navigation: ^4.1.1 => 4.3.3  </pre>
</details>

**Comment by brentvatne** [comment]
hi there! I believe for now you can work around this issue by installing jq: https://github.com/stedolan/jq

**Comment by mlecoq** [comment]
Thanks, I will try that

**Comment by cruzach** [comment]
As a workaround, you may want to try installing `jq` - https://github.com/stedolan/jq

**Comment by mlecoq** [comment]
@brentvatne @cruzach after jq install it works fine, thanks to both of you
