### ISSUE TITLE
Possibility to build an unpublished project

### ISSUE THREAD

**Issue by cwitteveen** [expo/turtle#210]
#### Motivation Behind Feature
The turtle-cli requires you to have an published expo project. So i first need to run either `expo publish` or run `expo export` and host the files myself. However, I have disabled OTA updates, which means that the bundles/assets are only fetched during the build fase of the app. This would mean that technically after building the app, the files should not need to be published anymore.

For my backend I use spring, and during the building of the backend, i inject the js bundles into the jar with gradle. So to update my js bundles i need to release a new version of my backend, and rebuild the docker container for it. All while the bundles are only ever used while i am building the app.

I think it would be nice if the turtle-cli either accepts localhost as `--public-url` or it accepts a directory where it can find the bundles and assets. This way the build can happen fully locally and I build the apk in the same pipeline as where i run `expo export`.

#### Feature Description
Add option to use a local directory to fetch the bundles,
or allow `--public-url` to be localhost.

#### Alternatives or Workarounds
Until a month ago the workaround for this was to simply use localhost as `--public-url`. However this commit 7f95b533ada86736c77d10b2b28120f9241ab6f4 added validation to `--public-url` which now prevents this. In order to still do this locally i go to my global node_modules folder and edit my local installation of turtle to remove the check for `https` so i can use localhost.

**Comment by VehpuS** [comment]
You can work around this by using ngrok, if you're looking for a solution in the meantime. Alternatively, use netlify for temporary hosting.

**Comment by papb** [comment]
I am facing the exact same issue. Thank you for sharing the workaround @cwitteveen.

**Comment by jameswilddev** [comment]
I've raised a PR for this but I can't build master so it is untested.

**Comment by dsokal** [comment]
@jameswilddev's PR has been merged. I'm closing this issue.
