### ISSUE TITLE
turtle android build fails with unknown option `--keystore-path'

### ISSUE THREAD

**Issue by mailantony05** [expo/turtle#215]
I am trying to build android apk file using expo/turtle.

I am able to export my files and see the dist folder created.

However when the build starts i am facing the below issue.

**error: --keystore-path.**

I have my .jks file downloaded from secure files into $(Build.SourcesDirectory)

Below is the command used for build.

turtle setup:android --sdk-version 36.0.0 EXPO_ANDROID_KEYSTORE_PASSWORD=$(KEYSTORE_PASSWORD) EXPO_ANDROID_KEY_PASSWORD=$(KEY_PASSWORD) turtle build:android --keystore-path $(Build.SourcesDirectory)/<app-name>.jks  -t apk --public-url https://127.0.0.1/dist/android-index.json

I have used the common name as app-name.jks than the actual name  for the issue description here

**Comment by wkozyra95** [comment]
- `EXPO_ANDROID_KEYSTORE_PASSWORD=$(KEYSTORE_PASSWORD)` is assigning empty string to `EXPO_ANDROID_KEYSTORE_PASSWORD`. You should use `${KEYSTORE_PASSWORD}` or `$KEYSTORE_PASSWORD`

- `$(Build.SourcesDirectory)/.jks` env variables can't have `.` in the name

- `$(Build.SourcesDirectory)/.jks` why did you add `/` there? Do you have file named `.jks`?


So after resolving all env variables, your command looks like this
```
EXPO_ANDROID_KEYSTORE_PASSWORD= EXPO_ANDROID_KEY_PASSWORD=  turtle build:android --keystore-path /.jks -t apk --public-url https://127.0.0.1/dist/android-index.json
```
