### ISSUE TITLE
Failed to build standalone app   err: Error: yarn exited with non-zero code: 1

### ISSUE THREAD

**Issue by almoret** [expo/turtle#216]
Im trying to build an apk file, but im facing the following error:

May 1 10:47:10 turtle[14551] ERROR: Failed to build standalone app
  err: Error: yarn exited with non-zero code: 1
      at ChildProcess.completionListener (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:286:20)
      at ChildProcess.emit (events.js:198:13)
      at ChildProcess.EventEmitter.emit (domain.js:448:20)
      at maybeClose (internal/child_process.js:982:16)
      at Socket.stream.socket.on (internal/child_process.js:389:11)
      at Socket.emit (events.js:198:13)
      at Socket.EventEmitter.emit (domain.js:448:20)
      at Pipe._handle.close (net.js:606:12)
      ...
      at spawnAsync (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at Object.spawnAsyncThrowError (/@expo/xdl@57.8.30/src/detach/ExponentTools.ts:100:19)
      at _installNodeModules (/usr/local/lib/node_modules/turtle-cli/src/bin/setup/android/index.ts:106:23)
  platform: "android"
MacBook-Air-de-Alex:react-new-app alexmoret$ expo diagnostics

  Expo CLI 3.20.1 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.7 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.20.1

Can, anyone, help me?

**Comment by dsokal** [comment]
Hi @almoret,
Could you please share the whole log output (look at the issue template)? The logline you posted is too generic to help you.

**Comment by almoret** [comment]
Hi @dsokal 

Thanks! Here is the whole log output

The manifest URL is: https://exp.host/@labmoonwalk/temakeria (​https://exp.host/@labmoonwalk/temakeria/index.exp?sdkVersion=37.0.0​). Learn more. (​https://expo.fyi/manifest-url​)
The project page is: https://expo.io/@labmoonwalk/temakeria (​https://expo.io/@labmoonwalk/temakeria​). Learn more. (​https://expo.fyi/project-page​)
MacBook-Air-de-Alex:react-new-app alexmoret$ export EXPO_USERNAME=XXXXXXXXX
MacBook-Air-de-Alex:react-new-app alexmoret$ export EXPO_PASSWORD=XXXXXXX
MacBook-Air-de-Alex:react-new-app alexmoret$ export EXPO_ANDROID_KEYSTORE_PASSWORD=XXXXXXXX
MacBook-Air-de-Alex:react-new-app alexmoret$ export EXPO_ANDROID_KEY_PASSWORD=kuerbis08
MacBook-Air-de-Alex:react-new-app alexmoret$ turtle build:android --keystore-path credentials/carambolah.keystore -t apk --keystore-alias br.com.moonwalk.temakeriaecia
May 4 09:35:10 turtle[1485] INFO:  shell app for SDK 37.0.0 doesn't exist, downloading...
  platform: "android"
  buildPhase: "setting up environment"
downloading [=================== ] 95% 0.7sMay 4 09:35:24 turtle[1485] INFO:  shell app has been downloaded
  platform: "android"
  buildPhase: "setting up environment"
May 4 09:35:24 turtle[1485] INFO:  extracting shell app (this may take a while)...
  platform: "android"
  buildPhase: "setting up environment"
May 4 09:35:28 turtle[1485] INFO:  shell app extracted
  platform: "android"
  buildPhase: "setting up environment"
May 4 09:35:28 turtle[1485] INFO:  installing dependencies in /Users/alexmoret/.turtle/workingdir/android/sdk37 directory...
  platform: "android"
  buildPhase: "setting up environment"
May 4 09:35:29 turtle[1485] INFO:  yarn install v1.17.3
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
May 4 09:35:29 turtle[1485] INFO:  info No lockfile found.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
May 4 09:35:29 turtle[1485] INFO:  [1/4] Resolving packages...
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
May 4 09:35:43 turtle[1485] INFO:  warning expo-cli > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:35:46 turtle[1485] INFO:  warning expo-cli > @expo/xdl > joi@14.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:35:50 turtle[1485] INFO:  warning expo-cli > @expo/xdl > joi > hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:35:50 turtle[1485] INFO:  warning expo-cli > @expo/xdl > joi > topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:35:50 turtle[1485] INFO:  warning expo-cli > @expo/xdl > joi > topo > hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:35:50 turtle[1485] INFO:  warning expo-cli > @expo/xdl > @expo/ngrok > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:35:50 turtle[1485] INFO:  warning expo-cli > @expo/xdl > probe-image-size > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:35:50 turtle[1485] INFO:  warning expo-cli > pacote > @npmcli/run-script > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:35:53 turtle[1485] INFO:  warning expo-cli > @expo/xdl > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:35:54 turtle[1485] INFO:  warning expo-cli > @expo/xdl > webpack > watchpack > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:35:57 turtle[1485] INFO:  warning expo-cli > @expo/xdl > @expo/webpack-config > react-dev-utils > fork-ts-checker-webpack-plugin > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:35:59 turtle[1485] INFO:  warning expo-cli > @expo/xdl > @expo/webpack-config > workbox-webpack-plugin > workbox-build > joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:35:59 turtle[1485] INFO:  warning expo-cli > @expo/xdl > @expo/webpack-config > workbox-webpack-plugin > workbox-build > joi > hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:35:59 turtle[1485] INFO:  warning expo-cli > @expo/xdl > @expo/webpack-config > workbox-webpack-plugin > workbox-build > joi > topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:35:59 turtle[1485] INFO:  warning expo-cli > @expo/xdl > @expo/webpack-config > workbox-webpack-plugin > workbox-build > joi > topo > hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:36:01 turtle[1485] INFO:  warning expo-cli > @expo/xdl > webpack-dev-server > chokidar > fsevents@1.2.12: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:36:06 turtle[1485] INFO:  warning expo-cli > @expo/package-manager > find-yarn-workspace-root > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:36:06 turtle[1485] INFO:  warning expo-cli > @expo/package-manager > find-yarn-workspace-root > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:36:17 turtle[1485] INFO:  warning workspace-aggregator-99a1fb5a-7037-44de-a721-da8feca6574f > expo-module-scripts > @babel/cli > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:36:18 turtle[1485] INFO:  warning workspace-aggregator-99a1fb5a-7037-44de-a721-da8feca6574f > expo-ads-facebook > fbemitter > fbjs > core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:36:21 turtle[1485] INFO:  warning workspace-aggregator-99a1fb5a-7037-44de-a721-da8feca6574f > jest-expo-puppeteer > babel-jest > @jest/transform > jest-haste-map > fsevents@1.2.12: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:36:22 turtle[1485] INFO:  warning workspace-aggregator-99a1fb5a-7037-44de-a721-da8feca6574f > jest-expo-enzyme > jest-enzyme > jest-environment-enzyme > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:36:23 turtle[1485] INFO:  warning workspace-aggregator-99a1fb5a-7037-44de-a721-da8feca6574f > jest-expo-puppeteer > jest-puppeteer > jest-environment-puppeteer > jest-dev-server > wait-on > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:36:23 turtle[1485] INFO:  warning workspace-aggregator-99a1fb5a-7037-44de-a721-da8feca6574f > jest-expo-puppeteer > jest-puppeteer > jest-environment-puppeteer > jest-dev-server > wait-on > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:36:24 turtle[1485] INFO:  warning workspace-aggregator-99a1fb5a-7037-44de-a721-da8feca6574f > jest-expo-enzyme > jest-enzyme > jest-environment-enzyme > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:36:27 turtle[1485] INFO:  [2/4] Fetching packages...
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
May 4 09:36:31 turtle[1485] INFO:  info @expo/traveling-fastlane-linux@1.13.1: The platform "darwin" is incompatible with this module.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
May 4 09:36:31 turtle[1485] INFO:  info "@expo/traveling-fastlane-linux@1.13.1" is an optional dependency and failed compatibility check. Excluding it from installation.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
May 4 09:36:31 turtle[1485] INFO:  error move-file@2.0.0: The engine "node" is incompatible with this module. Expected version ">=10.17". Got "10.16.0"
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:36:31 turtle[1485] INFO:  error Found incompatible module.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 4 09:36:31 turtle[1485] INFO:  info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
May 4 09:36:31 turtle[1485] ERROR: Failed to build standalone app
  err: Error: yarn exited with non-zero code: 1
      at ChildProcess.completionListener (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:286:20)
      at ChildProcess.emit (events.js:198:13)
      at ChildProcess.EventEmitter.emit (domain.js:448:20)
      at maybeClose (internal/child_process.js:982:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
      ...
      at spawnAsync (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at Object.spawnAsyncThrowError (/@expo/xdl@57.8.30/src/detach/ExponentTools.ts:100:19)
      at _installNodeModules (/usr/local/lib/node_modules/turtle-cli/src/bin/setup/android/index.ts:106:23)
  platform: "android"

**Comment by dsokal** [comment]
`The engine "node" is incompatible with this module. Expected version ">=10.17". Got "10.16.0"`
This is the culprit. Try upgrading node to at least 10.17.

**Comment by almoret** [comment]
So many thanks, @dsokal 

It worked!

Best,
Alex
