### ISSUE TITLE
Generated IPA contains .bak files

### ISSUE THREAD

**Issue by boris-burgos** [expo/turtle#219]
The generated IPA file contains two backup files:

Payload/ExpoKitApp.app/EXBuildConstants.plist.bak
Payload/ExpoKitApp.app/EXSDKVersions.plist.bak

I think those files are not necessary and should not be in the generated IPA.

**Comment by dsokal** [comment]
It's fixed in `turtle-cli@0.15.0`. Sorry it took us so long.
