### ISSUE TITLE
 turtle setup:android Timeout Issue. Setup the JAVA_OPTS for proxyhost and port

### ISSUE THREAD

**Issue by gadavell** [expo/turtle#220]
$ turtle setup:android 
May 6 16:07:43 turtle[13028] WARN:  Failed to check for turtle-cli update.
  err: Error: Unable to perform cache refresh for C:\Users\areddy\AppData\Local\Expo\turtle-cli-updates.json: TimeoutError: Promise timed out after 2000 milliseconds
      at Cacher.getAsync (C:\@expo\xdl@57.8.30\src\tools\FsCache.ts:107:15)
  platform: "android"
May 6 16:07:43 turtle[13028] INFO:  Downloading Android SDK
  platform: "android"
  buildPhase: "setting up environment"
May 6 16:07:53 turtle[13028] INFO:  Decompressing Android SDK
  platform: "android"
  buildPhase: "setting up environment"
May 6 16:08:24 turtle[13028] INFO:  Configuring Android SDK, this may take a while
  platform: "android"
  buildPhase: "setting up environment"
May 6 16:08:51 turtle[13028] INFO:  Warning: java.net.ConnectException: Connection timed out: connect
  platform: "android"

I did setup the JAVA_OPTS following properties but still getting the Timeout errors
-Dhttp.proxyHost=
-Dhttp.proxyPort=
-Dhttps.proxyHost=
-Dhttps.proxyPort

**Comment by wkozyra95** [comment]
Hi

turtle-cli is not supported on windows (https://docs.expo.io/distribution/turtle-cli/#for-android-builds)

**Comment by gadavell** [comment]
I  was able to successfully install on  windows 10 laptop  with Git BASH on  the environment where
we don't have to go through proxy to access the Internet. We are getting this  Issue only on the Windows 10 environments where we have to go through proxy to access the Internet.
