### ISSUE TITLE
Gradle log noise

### ISSUE THREAD

**Issue by dacevedo12** [expo/turtle#221]
### New Issue Checklist

- [x] Updated turtle-cli to the latest version (`yarn global add turtle-cli` or `npm install --global turtle-cli`).
- [x] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [x] I read [docs.expo.io](https://docs.expo.io) (Managed Workflow > Distributing Your App).
- [x] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).
- [ ] **I enclosed the complete output when running turtle, including the stack trace and command used.**

### Issue Description

When running build:android the logger outputs a lot of dots, which introduces noise for later analysis

##### Command executed

turtle build:android

##### Complete output when running turtle, including the stack trace and command used

<details>
  <img src="https://user-images.githubusercontent.com/29694570/81314323-9a5f3100-904e-11ea-8589-62fee0b69325.png"/>
</details>

### Environment

<details>
  <pre>
  Expo CLI 3.20.1 environment info:
    System:
      OS: Linux 4.15 Deepin 15 15.11
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 10.20.1 - /usr/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn
      npm: 6.14.4 - /usr/bin/npm
    npmPackages:
      expo: 37.0.8 => 37.0.8 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
</pre>
</details>

**Comment by dsokal** [comment]
It's fixed in https://github.com/expo/turtle/commit/0803811226645f2130f4510045e805b8042e627c
It'll be included in the next release of turtle-cli.
