### ISSUE TITLE
turtle setup:android  Failing with Timeout  even through proxy  settings are passed

### ISSUE THREAD

**Issue by gadavell** [expo/turtle#222]
**turtle setup for Android failing with TimeOut Error.
I did set the all the proxy settings that can think of see below.**
Environment Redhat Enterprise Linux 7.6

export JAVA_OPTS="-Dhttp.proxyHost=<proxyIp>-Dhttp.proxyPort=80 -Dhttps.proxyHost=<proxyIp> -Dhttps.proxyPort=80"

npm config set proxy   http://proxyIp:80
npm config set https-proxy   http://proxyIp:80
export http_proxy=http://proxyIp:80
export https_proxy=http://proxyIp:80

turtle-cli]$ turtle setup:android
May 7 14:19:06 turtle[30523] WARN:  Failed to check for turtle-cli update.
  err: Error: Unable to perform cache refresh for /home/oracle/.cache/expo/turtle-cli-updates.json: TimeoutError: Promise timed out after 2000 milliseconds
      at Cacher.getAsync (/@expo/xdl@57.8.30/src/tools/FsCache.ts:107:15)
      at Object.checkAsync (/@expo/xdl@57.8.30/src/tools/ModuleVersion.ts:22:43)
      at checkForUpdateAsync (./src/bin/index.ts:62:50)
      at Command.<anonymous> (./src/bin/index.ts:19:7)
  platform: "android"
May 7 14:19:06 turtle[30523] INFO:  Downloading Android SDK
  platform: "android"
  buildPhase: "setting up environment"
downloading [=================== ] 95% 0.4sMay 7 14:19:17 turtle[30523] INFO:  Decompressing Android SDK
  platform: "android"
  buildPhase: "setting up environment"
May 7 14:19:23 turtle[30523] INFO:  Configuring Android SDK, this may take a while
  platform: "android"
  buildPhase: "setting up environment"
May 7 14:21:30 turtle[30523] INFO:  Warning: java.net.ConnectException: Connection timed out (Connection timed out)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 7 14:27:52 turtle[30523] INFO:  Warning: Failed to download any source lists!
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 7 14:30:00 turtle[30523] INFO:  Warning: java.net.ConnectException: Connection timed out (Connection timed out)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 7 14:36:22 turtle[30523] INFO:  Warning: Failed to download any source lists!
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 7 14:36:22 turtle[30523] INFO:  Warning: Failed to find package platforms;android-28
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 7 14:38:29 turtle[30523] INFO:  Warning: java.net.ConnectException: Connection timed out (Connection timed out)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 7 14:44:51 turtle[30523] INFO:  Warning: Failed to download any source lists!
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 7 14:44:51 turtle[30523] INFO:  Warning: Failed to find package platform-tools
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
May 7 14:46:59 turtle[30523] INFO:  Warning: java.net.ConnectException: Connection timed out (Connection timed out)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"

**Comment by dsokal** [comment]
It seems this is a duplicated issue - https://github.com/expo/turtle/issues/225
