### ISSUE TITLE
gyp ERR! node -v v12.16.2

### ISSUE THREAD

**Issue by Rahulshahare** [expo/turtle#227]
warning "turtle-cli > @expo/xdl > @expo/dev-server > @expo/metro-config > metro-react-native-babel-transformer@0.58.0" has unmet peer dependency "@babel/core@*".
[4/4] Building fresh packages...
[-/5] ⠠ waiting...
[-/5] ⠠ waiting...
[-/5] ⠠ waiting...
[-/5] ⠠ waiting...
error /home/rahul/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /home/rahul/node_modules/sharp
Output:
info sharp Using cached /home/rahul/.npm/_libvips/libvips-8.9.0-linux-x64.tar.gz
ERR! sharp Please delete /home/rahul/.npm/_libvips/libvips-8.9.0-linux-x64.tar.gz as it is not a valid tarball
ERR! sharp zlib: unexpected end of file
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.16.2 | linux | x64
gyp info find Python using Python version 3.6.9 found at "/usr/bin/python3"
gyp http GET https://nodejs.org/download/release/v12.16.2/node-v12.16.2-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v12.16.2/node-v12.16.2-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v12.16.2/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v12.16.2/SHASUMS256.txt
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/rahul/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/rahul/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/rahul/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/rahul/.cache/node-gyp/12.16.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/rahul/.cache/node-gyp/12.16.2',
gyp info spawn args   '-Dnode_gyp_dir=/home/rahul/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/rahul/.cache/node-gyp/12.16.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/rahul/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/rahul/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:25:10: fatal error: vips/vips8: No such file or directory
 #include <vips/vips8>
          ^~~~~~~~~~~~
compilation terminated.
sharp.target.mk:137: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make: *** [Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory '/home/rahul/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/rahul/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.0-51-generic
gyp ERR! command "/home/rahul/.nvm/versions/node/v12.16.2/bin/node" "/home/rahul/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/rahul/node_modules/sharp
gyp ERR! node -v v12.16.2

**Comment by dsokal** [comment]
Hi @Rahulshahare,
Could you please fill out the issue template? Are you still experiencing this issue or you've managed to fix it? If so - what did you do?

**Comment by dsokal** [comment]
1. I just noticed this line in the log output you shared:
  `ERR! sharp Please delete /home/rahul/.npm/_libvips/libvips-8.9.0-linux-x64.tar.gz as it is not a valid tarball`
  I think the solution is to clear npm cache (or probably only deleting the above file) and then running the install command again.
2. I just verified that the latest version of `turtle-cli` is installable on a fresh docker container (`node:12.16.2`).
3. I'm closing this issue because I think the problem you experienced was transient and you haven't filled out the issue template. If you encounter this issue again, please open another issue.
