### ISSUE TITLE
Stuck on "Configuring Android SDK, this may take a while"

### ISSUE THREAD

**Issue by shahidcodes** [expo/turtle#240]
### New Issue Checklist

- [x] Updated turtle-cli to the latest version (`yarn global add turtle-cli` or `npm install --global turtle-cli`).
- [x] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [x] I read [docs.expo.io](https://docs.expo.io) (Managed Workflow > Distributing Your App).
- [x] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).
- [x] **I enclosed the complete output when running turtle, including the stack trace and command used.**

### Issue Description

I am trying to setup the turtle-cli. I followed steps from https://docs.expo.io/distribution/turtle-cli/?redirected but now when I am running `turtle setup:android --sdk-version 37.0.1`, it is stuck on "Configuring Android SDK, this may take a while"
##### Command executed

`turtle setup:android --sdk-version 37.0.1`

##### Complete output when running turtle, including the stack trace and command used

<details>
  <pre>
 Jul 16 00:31:59 turtle[164107] INFO:  Downloading Android SDK
  platform: "android"
  buildPhase: "setting up environment"
downloading [====================] 99% 0.3sJul 16 00:34:28 turtle[164107] INFO:  Decompressing Android SDK
  platform: "android"
  buildPhase: "setting up environment"
Jul 16 00:34:32 turtle[164107] INFO:  Configuring Android SDK, this may take a while
  platform: "android"
  buildPhase: "setting up environment"
</pre>
</details>

### Environment

<details>
  <pre>  Expo CLI 3.22.1 environment info:
    System:
      OS: Linux 4.15 Ubuntu 20.04 LTS (Focal Fossa)
      Shell: 5.0.16 - /bin/bash
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    npmPackages:
      @expo/webpack-config: ^0.12.12 => 0.12.12 
      expo: ~37.0.9 => 37.0.12 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.5 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.22.1</pre>
</details>

**Comment by dsokal** [comment]
Hi!

1. The "Configuring Android SDK ... " step can take a while if you have a slow internet connection. It installs a few Android SDKs, Android NDK, etc. Check out the script here - https://github.com/expo/turtle/blob/master/scripts/android/configureAndroidSdk.sh How long have you waited? Maybe you just need to what a little longer.
2. Can you rerun the command and tell me if you're still experiencing this issue?

**Comment by shahidcodes** [comment]
@dsokal I left it running overnight ( 6-8 hours ), in the morning it was still stuck at the same. I'll re-run it again.

**Comment by dsokal** [comment]
@shahidcodes any luck with this one?

**Comment by shahidcodes** [comment]
@dsokal problem is disappeared but I am not sure why. I updated to 0.17.0 before running the build this morning so it could be that. 
But now another problem is turtle can not find my app using URL (https://exp.host:443/@shahdicodes/app-name) on expo. I am passing my expo username and password to turtle. Could this be because my app privacy set to 'hidden'?

**Comment by dsokal** [comment]
Happy to hear you've managed to fix the original issue. Maybe you'd been experiencing some transient network issues?

Regarding your second issue - I suspect that you're passing `--public-url` as well as your Expo username and password at the same time.
1. If you're passing both, the public URL takes precedence. The username and password are disregarded. 
2. If you want your app to fetch updates from Expo servers you don't need to pass the `--public-url` option. Just pass the username and password.
3. I'm closing this issue as the second one is not related to the original topic. If you encounter more problems with turtle-cli please open separate issue.
