### ISSUE TITLE
How to specify release channel?

### ISSUE THREAD

**Issue by dolsem** [expo/turtle#26]
When building with expo-cli I can do `expo build:ios --release-channel prod`. How do I do this with turtle-cli?

**Comment by dolsem** [comment]
Running `turtle build:ios --help` answered my question. Still, I think it would be useful to mention in Expo docs that release channel can optionally be specified.

**Comment by amsimoes** [comment]
Still not present in the [docs page](https://docs.expo.io/distribution/turtle-cli/).

I'll probably open a PR sometime in the future, but just warning if it slipped...

**Comment by dons20** [comment]
Still not present in the docs.

**Comment by jailsonpaca** [comment]
> Still not present in the docs.

+ 1
