### ISSUE TITLE
ios builds keep failing.

### ISSUE THREAD

**Issue by mackbrowne** [expo/turtle#31]
I'm getting an error while turtle 'builds and signs ipa'

`/jenkins.plugins.nodejs.tools.NodeJSInstallation/10.15.3/lib/node_modules/turtle-cli/node_modules/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:39:21)`

This seems to intermittently break, and restarting the server sometimes fixes it and sometimes doesn't.  Any ideas?

**Comment by dsokal** [comment]
Hello @mackbrowne,
could you please provide us with some steps to reproduce this issue? That would be very helpful.

**Comment by mackbrowne** [comment]
I've confirmed its an issue when using turtle-cli with Jenkins using the NodeJS plugin.  That's all I got for you so far.  It runs fine locally, fails with that error on the signing process inside Jenkins.  Like I said, it was working a week ago and I've made no changes.

**Comment by dsokal** [comment]
Are there any more logs/errors? The logline you posted is too generic to help you, sorry.

**Comment by mackbrowne** [comment]
``` INFO [2019-04-02 10:29:44.22]: ▸ error: exportArchive: Code signing "ExpoKitApp.app" failed.
```rror Domain=IDEDistributionPipelineErrorDomain Code=0 "Code signing "ExpoKitApp.app" failed." UserInfo={NSLocalizedDescription=Code signing "ExpoKitApp.app" failed., NSLocalizedRecoverySuggestion=View distribution logs for more information.}
```

**Comment by dsokal** [comment]
Are you on Expo Developers Slack? If yes, please share the whole log file with me (my username: dsokal) if you don't want to share it here with the rest of the world. This still doesn't say anything.

**Comment by mackbrowne** [comment]
Doing this now!

**Comment by dsokal** [comment]
Discussed on Slack, it looks like it's a problem with Jenkins.

**Comment by mackbrowne** [comment]
It's true!
