### ISSUE TITLE
[build:ios] Error: codesign ident not present in find-identity

### ISSUE THREAD

**Issue by pnarielwala** [expo/turtle#327]
Hello!

I'm trying to build my ios expo app locally and I'm running into an issue with the `codesign ident`. Any help is really appreciated!

Thanks!

### New Issue Checklist

- [x] Updated turtle-cli to the latest version (`yarn global add turtle-cli` or `npm install --global turtle-cli`).
- [x] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [x] I read [docs.expo.dev](https://docs.expo.dev) (Managed Workflow > Distributing Your App).
- [x] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).
- [x] **I enclosed the complete output when running turtle, including the stack trace and command used.**

##### Command executed

```
$ expo fetch:ios:certs
$ turtle build:ios --team-id XXXXXXXX --dist-p12-path APP_dist.p12 --provisioning-profile-path APP.mobileprovision
```

##### Complete output when running turtle, including the stack trace and command used

<details>
  <pre> Aug 28 16:40:42 turtle[2790] INFO:  Cleaning up iOS...
  platform: "ios"
  buildPhase: "configuring NSBundle"
Aug 28 16:40:42 turtle[2790] INFO:  building and signing IPA
  platform: "ios"
  buildPhase: "building and signing IPA"
Aug 28 16:40:42 turtle[2790] INFO:  saved provisioning profile to temporary path
  platform: "ios"
  buildPhase: "building and signing IPA"
Aug 28 16:40:42 turtle[2790] INFO:  provisioning profile copied to home directory
  platform: "ios"
  buildPhase: "building and signing IPA"
Aug 28 16:40:42 turtle[2790] INFO:  done retrieving provisioning profile data
  platform: "ios"
  buildPhase: "building and signing IPA"
Aug 28 16:40:42 turtle[2790] INFO:  checking if teamID is present in keychain and that certificate is valid...
  platform: "ios"
  buildPhase: "building and signing IPA"
Aug 28 16:40:43 turtle[2790] INFO:  removed provisioning profile from the home directory
  platform: "ios"
  buildPhase: "building and signing IPA"
Aug 28 16:40:43 turtle[2790] ERROR: Error: codesign ident not present in find-identity: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Looking for identities matching "(XXXXXXXXXXXX)"
     0 valid identities found

    at Object.ensureCertificateValid (/@expo/xdl@59.1.0/src/detach/IosCodeSigning.js:18:11)
    at Object.build (/@expo/xdl@59.1.0/src/detach/IosIPABuilder.js:31:32)
    at buildAndSignIPA (/Users/parthnarielwala/.nvm/versions/node/v14.17.5/lib/node_modules/turtle-cli/src/builders/ios/archive.ts:58:3)
    at Object.buildArchive [as default] (/Users/parthnarielwala/.nvm/versions/node/v14.17.5/lib/node_modules/turtle-cli/src/builders/ios/archive.ts:20:5)
    at iosBuilder (/Users/parthnarielwala/.nvm/versions/node/v14.17.5/lib/node_modules/turtle-cli/src/builders/ios/index.ts:33:7)
    at /Users/parthnarielwala/.nvm/versions/node/v14.17.5/lib/node_modules/turtle-cli/src/bin/utils/builder.ts:87:7
    at Command.<anonymous> (/Users/parthnarielwala/.nvm/versions/node/v14.17.5/lib/node_modules/turtle-cli/src/bin/index.ts:23:12)
  platform: "ios"
Aug 28 16:40:43 turtle[2790] INFO:  delete keychain...
  platform: "ios"
  buildPhase: "deleting keychain"
Aug 28 16:40:43 turtle[2790] INFO:  deleting keychain...
  platform: "ios"
  buildPhase: "deleting keychain"
Aug 28 16:40:50 turtle[2790] INFO:  done deleting keychain
  platform: "ios"
  buildPhase: "deleting keychain"
Aug 28 16:40:50 turtle[2790] ERROR: Failed to build standalone app
  err: Error: codesign ident not present in find-identity: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  Looking for identities matching "(XXXXXXXXXXXX)"
       0 valid identities found
  
      at Object.ensureCertificateValid (/@expo/xdl@59.1.0/src/detach/IosCodeSigning.js:18:11)
      at Object.build (/@expo/xdl@59.1.0/src/detach/IosIPABuilder.js:31:32)
      at buildAndSignIPA (/Users/parthnarielwala/.nvm/versions/node/v14.17.5/lib/node_modules/turtle-cli/src/builders/ios/archive.ts:58:3)
      at Object.buildArchive [as default] (/Users/parthnarielwala/.nvm/versions/node/v14.17.5/lib/node_modules/turtle-cli/src/builders/ios/archive.ts:20:5)
      at iosBuilder (/Users/parthnarielwala/.nvm/versions/node/v14.17.5/lib/node_modules/turtle-cli/src/builders/ios/index.ts:33:7)
      at /Users/parthnarielwala/.nvm/versions/node/v14.17.5/lib/node_modules/turtle-cli/src/bin/utils/builder.ts:87:7
      at Command.<anonymous> (/Users/parthnarielwala/.nvm/versions/node/v14.17.5/lib/node_modules/turtle-cli/src/bin/index.ts:23:12)
  platform: "ios"</pre>
</details>

### Environment

<details>
  <pre> Expo CLI 4.11.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: 42.0.3 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: managed</pre>
</details>

**Comment by brentvatne** [comment]
https://forums.expo.dev/t/build-fails-on-ios-probably-due-to-newly-enabled-2fa/33306/2?u=notbrent

**Comment by rcrvano** [comment]
My certificates are valid and not expired!
I can build my app using Expo Cloud 
```
expo build:ios
```

but I want to build app locally
I fetched active certificates from Expo Cloud using
```
expo fetch:ios:certs
```
and then I try to build ipa locally

```
EXPO_IOS_DIST_P12_PASSWORD=<PASS FOR p12> turtle build:ios --team-id <TEAM_ID_10_DIGIT> --dist-p12-path ./certs/ios/dist.p12  --provisioning-profile-path ./certs/ios/mobileprovision--type archive 
```

**Comment by thonatos** [comment]
> building and signing  IPA with those steps .

1. login xcode with my developer account.
2. clear certs in keychain (dev & dist certs)
3. run `turtle build:ios` again .

**Comment by pnarielwala** [comment]
UPDATE: My certs also were active and not expired and followed all the above solutions and still couldn't figure it out until I installed the certificate on this forum answer post https://developer.apple.com/forums/thread/662300 and it worked!

**Comment by rcrvano** [comment]
Thanks a lot, @pnarielwala !

Just need to update this certificate
https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer
