### ISSUE TITLE
Why is Turtle failing in CI

### ISSUE THREAD

**Issue by samchouse** [expo/turtle#349]
### Question Checklist

- [x] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [x] I read [docs.expo.dev](https://docs.expo.dev) (Managed Workflow > Distributing Your App).
- [x] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).

### Question Subject

Running Turtle in CI fails but it should build fine. Why?

#### Question Description

I want Turtle to build in my CI but it doesn't seem to be [working](https://github.com/Xenfo/utils/runs/3956801614?check_suite_focus=true). I've got no clue why as it works perfectly on my machine.

**Comment by brentvatne** [comment]
it looks like you're running the command in a directory without the expo package installed
