### ISSUE TITLE
turtle and ssl pinning - added 3rd party certificate is not included in the build

### ISSUE THREAD

**Issue by priitserk** [expo/turtle#353]
We are using SSL pinning solution described here
https://github.com/MaxToyberman/react-native-ssl-pinning

To make it happen, we are including our intermediate certificate (.CER) in the solution. Everything works in local simulators. But when we are building the binaries with turtle, our certificate is just ignored and not included in the build. Turtle just ignores the file. 

Any ideas what to do?

**Comment by wkozyra95** [comment]
turtle-cli is the equivalent of a classic expo build that runs on local machine, there is no way to include any libraries with native components, only expo packages and few specific react-native libraries, can be used here.

We just released new service EAS that supports third-party libraries, with auto-linking it should work out of the box, if any manual steps are required writing config plugins or ejecting might be necessary.
https://docs.expo.dev/eas/
