### ISSUE TITLE
Unable to build Android app on Windows

### ISSUE THREAD

**Issue by aamir0** [expo/turtle#39]
When running `turtle build:android` on Windows (turtle version **0.6.0**), I get an error stating that it's not supported on my OS:

```
C:\ExpoAppDir>turtle build:android
Apr 10 11:05:32 turtle[6772] ERROR: Failed to build standalone app
  err: Error: We don't support running standalone app builds for this platform on your operating system
      at C:\Users\aamir0\AppData\Roaming\npm\node_modules\turtle-cli\src\bin\utils\builder.ts:32:15
      at Command.action (C:\Users\aamir0\AppData\Roaming\npm\node_modules\turtle-cli\src\bin\index.ts:23:18)
  platform: "ios"
  environment: null
```

When I place some `console.log` statements before it throws the error, I see that `osList` == `[ 'darwin', 'linux' ]` and `process.platform` == `win32`. This checks out with
[android.ts](https://github.com/expo/turtle/blob/master/src/bin/commands/build/android.ts):32, but after asking on Slack, it doesn't sound like Windows being excluded is an intentional restriction.

Also, even though it logs `platform:"ios"`, I can tell it's targeting Android, since using `turtle build:ios` gives `osList` == `[ 'darwin' ]` as expected. The platform being incorrect also seems to be an issue, but I'm not worried about that right now.

**Comment by CarlosEscobarBlasco** [comment]
Any news about this problem?

**Comment by dsokal** [comment]
Windows is not a supported platform, sorry.
