### ISSUE TITLE
Error on turtle android setup

### ISSUE THREAD

**Issue by marcoamt** [expo/turtle#397]
### New Issue Checklist

- [X] Updated turtle-cli to the latest version (`yarn global add turtle-cli` or `npm install --global turtle-cli`).
- [X] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [X] I read [docs.expo.dev](https://docs.expo.dev) (Managed Workflow > Distributing Your App).
- [X] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).
- [X] **I enclosed the complete output when running turtle, including the stack trace and command used.**

### Issue Description

I'm having following error while setting up android with latest version requiring JDK 11:

`Apr 11 23:33:02 turtle[11709] ERROR: Failed to setup environment for android builds
  err: Error: spawn ./configureAndroidSdk.sh ENOENT
      at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
      at onErrorNT (node:internal/child_process:476:16)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)
  platform: "android"`

##### Command executed

`turtle setup:android`

##### Complete output when running turtle, including the stack trace and command used

`Apr 11 23:32:59 turtle[11709] INFO:  Downloading Android SDK
  platform: "android"
  buildPhase: "setting up environment"
downloading [==================  ] 90% 0.2sApr 11 23:33:01 turtle[11709] INFO:  Decompressing Android SDK
  platform: "android"
  buildPhase: "setting up environment"`

`Apr 11 23:33:02 turtle[11709] INFO:  Configuring Android SDK, this may take a while
  platform: "android"
  buildPhase: "setting up environment"`

`Apr 11 23:33:02 turtle[11709] INFO:  ./configureAndroidSdk.sh: line 5: /Users/user/.turtle/androidDependencies/sdk/cmdline-tools/tools/bin/sdkmanager: No such file or directory
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"`

`Apr 11 23:33:02 turtle[11709] INFO:  ./configureAndroidSdk.sh: line 14: /Users/user/.turtle/androidDependencies/sdk/cmdline-tools/tools/bin/sdkmanager: No such file or directory
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"`

`Apr 11 23:33:02 turtle[11709] INFO:  ./configureAndroidSdk.sh: line 15: /Users/user/.turtle/androidDependencies/sdk/cmdline-tools/tools/bin/sdkmanager: No such file or directory
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"`

`Apr 11 23:33:02 turtle[11709] ERROR: Failed to setup environment for android builds
  err: Error: spawn ./configureAndroidSdk.sh ENOENT
      at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
      at onErrorNT (node:internal/child_process:476:16)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)
  platform: "android"`

**Comment by jhogervorst** [comment]
@marcoamt I’m running into the same issue. (How) did you solve it?

**Comment by marcoamt** [comment]
@jhogervorst I resinstalled node using homebrew and it solves for me.
