### ISSUE TITLE
Release of the Expo SDK 45 tarball

### ISSUE THREAD

**Issue by hshyk** [expo/turtle#399]
### Question Checklist

- [x] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [x] I read [docs.expo.dev](https://docs.expo.dev) (Managed Workflow > Distributing Your App).
- [x] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).

### Question Subject
Looking for the release of the Expo SDK 45 tarball.

#### Question Description
When trying to build an Expo app locally, it is blocked on the tarball not being available in https://github.com/expo/turtle/tree/master/shellTarballs. 

```
Failed to build standalone app
  err: Error: ENOENT: no such file or directory, open '/Users/xxxxxx/.config/yarn/global/node_modules/turtle-cli/shellTarballs/ios/sdk45'
  platform: "ios"

```

**Comment by wkozyra95** [comment]
As mentioned in the release blogpost https://blog.expo.dev/expo-sdk-45-f4e332954a68
support for sdk45 in classic builds(and turtle-cli) will land a bit later, you can subscribe for releases on this repo to be notified.
