### ISSUE TITLE
ERROR: Failed to setup environment for android builds

### ISSUE THREAD

**Issue by superyarik** [expo/turtle#45]
trying to [install turtle](https://docs.expo.io/versions/latest/distribution/turtle-cli/#install-turtle-cli) for build application with branch. ([blog post](https://blog.expo.io/changes-to-expo-branch-support-d002c4bc564e))
i can not install jdk 8, its unavailable from oracle servers, so latest installed.
also i install turtle-cli@0.5.15

run command
turtle setup:android --sdk-version 32.0.0

face this
Apr 17 13:08:57 turtle[8262] ERROR: Failed to setup environment for android builds
  err: Error: Process exited with non-zero code: 1
      at ChildProcess.child.on (/usr/local/lib/node_modules/turtle-cli/node_modules/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:39:21)
      at emitTwo (events.js:126:13)
      at ChildProcess.emit (events.js:214:7)
      at maybeClose (internal/child_process.js:925:16)
      at Socket.stream.socket.on (internal/child_process.js:346:11)
      at emitOne (events.js:116:13)
      at Socket.emit (events.js:211:7)
      at Pipe._handle.close [as _onclose] (net.js:557:12)
  platform: "ios"
  environment: null

how i can fix it?

**Comment by dsokal** [comment]
Hello @superyarik,
are these the only logs you're getting or is there anything more? Unfortunately, the error you posted is too generic to help you. 

Additional questions:
1) Are you running turtle-cli locally or on some CI?
2) What operating system do use?
3) Are you sure you have `javac` and `npm`/`yarn` in your path? Checking if these things exist could cause this error.

**Comment by superyarik** [comment]
localy on my mac
macos 10.14.4
javac and npm/yarn is running from terminal
$javac -version
javac 12

$npm -v
6.2.0

**Comment by dsokal** [comment]
@superyarik are there any more logs?

**Comment by superyarik** [comment]
[log.txt](https://github.com/expo/turtle/files/3093915/log.txt)
this is full log from console. if you can say where i can find more - i will make it.

**Comment by dsokal** [comment]
Ok, so I'm almost sure right now that the problem is with JDK version you have. turtle-cli hasn't been tested with the latest version of JDK. 

What do you mean JDK 8 is not available on Oracle servers? It's there - https://www.oracle.com/technetwork/java/javaee/downloads/jdk8-downloads-2133151.html

**Comment by superyarik** [comment]
im trying to install it via brew and get error

$brew cask install java8                              
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/core, homebrew/cask and caskroom/versions).
==> Updated Formulae
pcre2

==> Caveats
Installing java8 means you have AGREED to the license at:
  https://www.oracle.com/technetwork/java/javase/terms/license/javase-license.html

==> Satisfying dependencies
==> Downloading https://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jdk-8u202-macosx-x64.dmg
==> Downloading from https://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jdk-8u202-macosx-x64.

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'java8' with message: Download failed: https://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jdk-8u202-macosx-x64.dmg

**Comment by dsokal** [comment]
Please try to download and install it manually.

**Comment by superyarik** [comment]
@dsokal yep, manual install java 8 fix problem. Thank you!
