### ISSUE TITLE
turtle doesn't read buildNumber and versionCode from local app.json

### ISSUE THREAD

**Issue by metro-tiwen** [expo/turtle#48]
### Problem:
When app.json is supplied using `--config`, the buildNumber and versionCode is still from previously published app.json, not from the local app.json file.

### Use case:
I'm trying to setup my CI & CD workflow with Circle CI that follows these steps:
1. build standalone apps using turtle-cli
2. upload the standalone app to app stores with `fastlane`.

One requirement is that I want the `buildNumber` and `versionCode` to be populated during build time using CIRCLE_BUILD_NUM. I'm very certain that the app.json on CI servers are properly updated, however it seems like turtle still picks up `expo.ios.buildNumber` and `expo.android.versionCode` from latest published app.json.

### Other notes:
The command I used:
```
turtle build:android \
  --keystore-path ./admin-native.jks \
  --keystore-alias $EXPO_ANDROID_KEYSTORE_ALIAS \
  --config ~/expo-project/app.json \
  -o ~/expo-project/admin-native.apk
```

And turtle-cli version is 0.6.0.

**Comment by dsokal** [comment]
Hello @metro-tiwen,
it's not a bug. I believe we should update the docs, so they make it clear that turtle-cli doesn't use `app.json` as the source of truth, but it either fetches the manifest from Expo servers or from `--public-url` passed to turtle command.
Therefore to change your `buildNumber` and/or `versionCode` you should publish your app.
I created another issue - https://github.com/expo/turtle/issues/49

Thanks for reporting anyway.
