### ISSUE TITLE
Add note in docs about manifest being used in Turtle

### ISSUE THREAD

**Issue by dsokal** [expo/turtle#49]
Related: https://github.com/expo/turtle/issues/48

We should make it clear in docs that turtle-cli doesn't use `app.json` as the source of truth for things such as `buildNumber` and `versionCode`. Basically, the whole manifest which includes almost all configuration options is fetched either from Expo servers (when a user uses `expo publish` to publish his app) or from `--public-url` passed to `turtle` command.

**Comment by VehpuS** [comment]
It would also be useful to clarify what in formation *is* used from the app.json file.

**Comment by zainulabidin302** [comment]
I just wanted to share my experience with this issue.
So I used a script to build my application with turtle but I don't use expo build service.


```
# build.sh

export ANDROID_HOME=
export EXPO_USERNAME=
export EXPO_PASSWORD=
export EXPO_ANDROID_KEYSTORE_PASSWORD=
export EXPO_ANDROID_KEY_PASSWORD=
expo publish # in order to update manifest on server https://github.com/expo/turtle/issues/49
turtle build:android --keystore-path /Users/....jks --keystore-alias ...
```


This way, with the `expo publish` line in my script, I first update the manifest on the expo server,  and then I use turtle build which uses manifest from server.

This solves my problem.
