### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zularizal** [expo/turtle#51]
Hi @dsokal I'm a graphic designer. I like your project, I want to contribute by creating a free logo for your project. What do you think?

**Comment by dsokal** [comment]
Hello @zularizal,
It would be great if you could create a logo for turtle :) I'm looking forward to it.

**Comment by zularizal** [comment]
Okay, I need time to make it. And I will send it in the next reply.

**Comment by zularizal** [comment]
Hi @dsokal , this is the design logo for your project. This logo is inspired by tortoise objects and command line. What do you think? Which one do you like?

If there is something you want to change, let me know.

![bitmap](https://user-images.githubusercontent.com/38547278/57270332-08c48880-70b5-11e9-8b1f-61c04a821547.png)

**Comment by dsokal** [comment]
Hello @zularizal,
your designs look great! Thank you for taking the time to create these.

I think the best one is number 2, but could you try to make the colors consistent with what we have on our website? I'm talking about the blue color we use there. The hex values are:
```
expo color darker - #4630EB
expo color - #4630EB
expo color (lighter) - #5844ed
```

Also, I have another small request. Could you please also create another version of number 2 (with blue colors as well) using the Expo logo (exponent sign) somewhere in there? I'd love to see how would it look like with it, although it could not make sense to use it here.

Thanks so much!

**Comment by zularizal** [comment]
Here are some logo colors. The color is based on the color you gave before.

And below it is a logo that is combined with an exponent sign. What do you think about this?

![bitmap](https://user-images.githubusercontent.com/38547278/57283164-b6955e80-70d8-11e9-8231-a792bc9d49e8.png)

**Comment by dsokal** [comment]
Oh, sorry, I meant either of these:
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg width="140px" height="164px" viewBox="-2 -1 26 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <path
      fill="#000020"
      fillRule="evenodd"
      d="M5.84439563e-15,18.52072 C0.042601976,19.0415198 0.225318565,19.5638181 0.704130384,20.2650123 C1.27202197,21.0966169 2.24914731,21.5536071 2.9619004,20.8204258 C3.44287509,20.3256353 8.643748,11.2343287 11.1501969,7.78933904 C11.4511295,7.3640867 12.0728268,7.3640867 12.3739317,7.78933904 C14.8803807,11.2343287 20.0812536,20.3256353 20.5622283,20.8204258 C21.2748089,21.5536071 22.2521067,21.0966169 22.8199983,20.2650123 C23.3790947,19.4462456 23.5343035,18.8713971 23.5343035,18.2580353 C23.5343035,17.8402716 15.4344759,2.76636898 14.6187677,1.5116517 C13.8343003,0.304828919 13.5946623,0.042335452 12.268059,0 L11.2560275,1.79395598e-12 C9.92932506,0.042335452 9.68981105,0.304828919 8.90518853,1.5116517 C8.10659328,2.74030565 0.3230204,17.219996 0,18.213285 L5.84439563e-15,18.52072 Z"
    />
  </svg>
```

```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg width="140px" height="164px" viewBox="0 0 140 164" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 54.1 (76490) - https://sketchapp.com -->
    <title>mobile</title>
    <desc>Created with Sketch.</desc>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round">
        <g id="mobile" transform="translate(1.000000, 1.000000)" fill-rule="nonzero" stroke-width="3">
            <polygon id="Path" stroke="#000020" fill="#FFFFFF" points="41.27 24.18 82.15 0.5 93.95 7.14 53.06 30.82"></polygon>
            <polygon id="Path" stroke="#00001F" fill="#FFFFFF" points="95.7 160.64 82.03 152.25 44.8 63.19 10.04 110.49 0.5 104.89 41.27 24.18 53.06 30.82"></polygon>
            <polygon id="Path" stroke="#000020" fill="#000000" points="10.04 110.49 53.73 84.57 44.8 63.19"></polygon>
            <path d="M120.67,97.13 C108.294664,97.1335542 97.4483402,88.8530647 94.1901963,76.9143278 C90.9320523,64.9755909 96.0684491,52.333333 106.73,46.05 L94,7.14 L53.06,30.82 L95.7,160.64 L136.59,137 L123.46,97 C122.53277,97.0901207 121.601592,97.133509 120.67,97.13 L120.67,97.13 Z" id="Path" stroke="#000020" fill="#000000"></path>
            <circle id="Oval" stroke="#00001F" fill="#FFFFFF" cx="120.51" cy="69.72" r="14.71"></circle>
            <path d="M133.17,62.22 C131.408731,72.6150654 122.403218,80.2217871 111.86,80.22 C111.28,80.22 110.71,80.22 110.14,80.15 C115.40075,85.3304646 123.686646,85.8086045 129.508373,81.2676574 C135.3301,76.7267103 136.88373,68.5737405 133.14,62.21 L133.17,62.22 Z" id="Path" stroke="#000020" fill="#000000"></path>
        </g>
    </g>
</svg>
```

**Comment by zularizal** [comment]
Hi @dsokal , here are the original and new versions.
I took the background color on the logo from the color reference that you previously sent # 000020. And on the second version I tried it in blue.

What do you think?

![bitmap](https://user-images.githubusercontent.com/38547278/57347690-615f5880-717d-11e9-9d07-e189c237ec12.png)

**Comment by dsokal** [comment]
We think that the new green version (NEW VERSION 1) is the best and if you don't mind we'd like to use it as the official Turtle CLI logo :)

Could you please share the high-quality version of it? I think we'll need a version with a transparent background. If you have a vector version it would be the best.

Thanks so much for taking the time for creating this design! That's really great. 🎉

**Comment by zularizal** [comment]
Hi @dsokal , I sent a pull request

And also I have uploaded the logo in vector format to the drive. Check this link.

https://drive.google.com/open?id=1XCrEoSsADfhJuXF06rXtlD29SKGlk61H

**Comment by dsokal** [comment]
Hello @zularizal,

sorry for bothering you, but as long as we appreciate the work you put into creating the logo design, we also need to confirm few things.

Could you please answer these questions?
1. Do you let use the logo exclusively? (i.e. you won't share it with someone else who also wants to use it)
2. Do you let us use it in both digital and physical forms?
3. Are we allowed to make changes to the logo if we need that? (like adjusting the color)
4. Do you let us use it and you don't want payment now or royalties later (say, if we were to charge for Turtle-related services, or let people buy Expo swag online)?

Thanks again for the logo, it looks awesome.
