### ISSUE TITLE
Cannot find module 'bunyan'

### ISSUE THREAD

**Issue by dacevedo12** [expo/turtle#56]
Just installed turtle-cli 0.7.1 and it throws that error.

**Comment by dsokal** [comment]
Hello,
that's strange, it installs and works fine on CI - https://circleci.com/gh/expo/turtle-cli-example/133
Could you maybe try reinstalling `turtle-cli`? `yarn global add turtle-cli` or `npm install -g turtle-cli`
Let me know if that helps. If not, please provide more details (node version/npm version/operating system) - basically, you can provide the output of `expo diagnostic` command.

Thanks!

**Comment by dacevedo12** [comment]
Hi, thanks for your fast answer.

I tried removing node_modules/ and reinstalling turtle-cli from npm (0.7.1) but the error remains. I also tried running it in our CI runner (debian buster running node 10.x) but it throws the same.

![image](https://user-images.githubusercontent.com/29694570/57332794-18f25d00-70e1-11e9-9873-e5068e6af078.png)

**Comment by dsokal** [comment]
From where did you try removing `node_modules` directory? `turtle-cli` should be installed globally.

node 10.x shouldn't be a problem as well. 
- I just installed v10.15.3
- Ran `rm -rf /Users/dsokal/.config/yarn/global/node_modules/`
- Then `yarn global add turtle-cli`
- `turtle --help` works fine

I think you're doing something wrong.

**Comment by dacevedo12** [comment]
You were right, i solved it by installing turtle-cli globally but noticed that adding bunyan to our package.json works too. Thanks a lot!

Also, this might be a good thing to document since other people might thing -g is optional and will get this error too.

**Comment by john20xdoe** [comment]
Got this error too on 0.12.2 turtle-cli, running on a Jenkins machine.
Had to specify `bunyan` in devDependencies since cannot install turtle-cli globally (there is another version there used by another project).
