### ISSUE TITLE
Illegal option when using `expo build:android` with a keystore alias that starts with "-"

### ISSUE THREAD

**Issue by zaytrix** [expo/turtle#60]
## Description

I am manually uploading an existing keystore using `expo build:android`, and the alias that I need to use has a leading "-", for example: `-myAlias`. When prompting for the keystore alias, that's what I type in.
```console
? Keystore Alias: -myAlias
```

## Expected Behavior

I thought it would work fine, I even tried all of these options to attempt to escape the "-" character: https://stackoverflow.com/a/26453747

## Observed Behavior

It seemed like everything was successful, but I was unable to install the app, so I checked the build logs and saw this under signing created apk:
```console
[stderr] Illegal option: -myAlias
Please type jarsigner -help for usage
jarsigner exited with non-zero code: 1
```

## Environment

I am using Expo Cli 2.17.0

**Comment by dsokal** [comment]
Hello @zaytrix,
thanks for reporting. Unfortunately, there is nothing we can do about it. This is how `jarsigner` works and we're not going to change the way we sign .apk files for SDK 31 (this is the version you're using). It was changed in SDK 32 and we don't use `jarsigner` there.
You have two options here: you can either change the alias in your keystore or upgrade your project to SDK 32.

**Comment by zaytrix** [comment]
I've upgraded my project to SDK 33 and I can confirm that it works!
