### ISSUE TITLE
Support Universal Modules in turtle in order to enable customizable builds

### ISSUE THREAD

**Issue by terribleben** [expo/turtle#7]
## Goals

1. The default `exp build` behavior should do the same thing it does now, provide all modules. (we might change this later.)
2. For advanced users, there should be a way to customize their build to omit unneeded or unwanted native code. I'm guessing probably a key in `app.json`.

  - Use case 1: **Thin builds**. The user just wants the smallest ipa/apk possible and does not plan to use more APIs in an over-the-air update, so they know they can omit many of our native modules.
  - Use case 2: **Omit specific modules.** The user just wants to remove one or two specific modules (for example, they don't want the "Uses Ads" flag to show up on their Google Play listing, so they remove just the ads API. https://github.com/expo/expo/issues/1789 )

3. We should still avoid running on-demand `xcodebuild` whenever possible in order to save time and resources.

## Prerequisites

- Our SDK needs to be (at least partially) modular. We're shipping the first set of Universal Modules within the Expo runtime in SDK 29. So far, only a small handful of our modules have been converted to universal modules. I don't think we need to wait for 100% universal modules before proceeding with this turtle project.
- To simplify the dependency picture, we can ship standalone apps with single-SDK support. We should do this before we introduce further complexity. Ticket here: https://github.com/expo/universe/issues/2366

## Turtle details

Mostly TBD. We probably need to construct a matrix of build caches (instead of having just a single build per release) on the server. The turtle agent can check to see if it has a cached artifact for the user's module configuration, and if not, build one. We may also need to stop running the build our CI machines and do it on the turtle machines instead? There is a (probably old, outdated) description of this here: https://github.com/expo/universe/issues/2032

On iOS, optional module dependencies are expressed with cocoapods. I think on Android they are gradle deps. So the agent will probably need to generate the correct Podfile/gradle file in order to assemble a build.

Lastly, certain parts of the native bundle configuration step will change depending on used modules. As one simple example, we only need to configure `NSCameraUsageDescription` for builds which use the camera. That means we might need a way for each module to express its own "configure step" in JS.

**Comment by wkozyra95** [comment]
Short description of how will changes in all repos work together
- expo-cli (https://github.com/expo/expo-cli/pull/528)
  read package.json and send it with a manifest to the server when publishing
- www (https://github.com/expo/universe/pull/3504)
  extract `dependencies` field from package.json and add it to manifest
- turtle (https://github.com/expo/turtle/pull/47)
  resolve unimodules using `dependencies` field in manifest and `packages` directory in `expo/expo`, the final list of unimodules is passed to xdl build function.
- xdl(https://github.com/expo/expo-cli/pull/528)
 create directory `enabled-modules` in shellapp and symlinks to `packages` for every package from list.
- expo/expo (https://github.com/expo/expo/pull/4025)
  autoinstall all packages form `enabled-modules` directory using script from `unimodules/react-native-unimodules`
- react-native-unimodules (https://github.com/unimodules/react-native-unimodules/pull/28)
  - add support for maven dependencies
  - generate java file with list of pacakges `BasePackageList.java`

**Comment by wkozyra95** [comment]
released in sdk33
