### ISSUE TITLE
Memory leak after build

### ISSUE THREAD

**Issue by dacevedo12** [expo/turtle#70]
turtle-cli is not killing java process after a succesful build:android.

**Comment by dsokal** [comment]
@dacevedo12 could you please provide more details?

**Comment by dacevedo12** [comment]
After playing with turtle for a while, I discovered that this memory leak was just a misconfiguration on my part. I forgot to set the env variables to limit java's max RAM consumption and also gradle. I saw this in the example, but we should consider this as an opportunity to add docs on those env variables.

Greetings,

**Comment by dacevedo12** [comment]
Following up my previous comment, I was referring to the following env variables: https://github.com/expo/turtle/blob/master/k8s/android/turtle-deployment.template.yml#L141
