### ISSUE TITLE
💡 Use sdkVersions as build flavors, not versions

### ISSUE THREAD

**Issue by sjchmiela** [expo/turtle#76]
If we treat current `sdkVersion` of a job not as a version of something, but rather a flavor of a build:
- we could easily implement multiple flavors for one SDK version (eg. SDK33 without Branch, SDK33 with Branch, SDK33 Expo Client, SDK33 standalone app)
- it would be more extensible for Turtle users.

**Comment by dsokal** [comment]
This will be addressed in Turtle v2. I'm closing this issue.
