### ISSUE TITLE
Android: build standalone app on MAC

### ISSUE THREAD

**Issue by francescotimperi** [expo/turtle#79]
I setup turtle cli in my expo project and executed the initial setup for android build and everything seems to be fine.

When launching turtle build for android the script ends with such an error

```
Jun 6 18:26:26 turtle[2514] ERROR: Error: ../../tools-public/check-dynamic-macros-android.sh exited with non-zero code: 134
    at ChildProcess.completionListener (/Users/franz/npm/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)

```

Any idea?!

**Comment by dsokal** [comment]
Hello @francescotimperi,

could you please remove `~/.turtle/workingdir` directory and run `turtle setup:android` again? I guess something might have gone wrong there. Let me know if that helps.

**Comment by francescotimperi** [comment]
Hi @dsokal actually I purged many times my ~/.turtle/workingdir and after a while i got an error about the node version I'm using. I had installed 8.9.4, but it looks like I needed at least 8.10.0. 

I update node via brew but I got version 12.0.0 for which it is not possible to install turtle successfully, as there are some compilation errors during turtle installation. So I need to perform a manual node installation and repeat the setup apaprently..

**Comment by francescotimperi** [comment]
After upgrading to sdk33 and turtle cli 0.8.2 I´m still facing the same issue....so i re-open the previous issue.

using node 10.16.0
yarn 1.16.0
turtle cli 0.8.2

Running build on MAC OS.

Attached a full trace of build process with final error. I removed the entire ~/.turtle but I´m always getting same error.

[error_log.txt](https://github.com/expo/turtle/files/3277666/error_log.txt)

**Comment by dsokal** [comment]
@francescotimperi 
I think it's not an issue with turtle-cli, but rather with your system.
```
Jun 11 19:01:52 turtle[3286] INFO:  dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.7.dylib
```

One of the first results in google:
https://github.com/atomantic/dotfiles/issues/23#issuecomment-298784915

Please try doing the same and let me know if the issue goes away.

**Comment by francescotimperi** [comment]
@dsokal 

As suggested reinstalling gawk and readline via brew solved the problem. Thanks for having spotted the issue.
