### ISSUE TITLE
Build android fails in circleCI

### ISSUE THREAD

**Issue by mackbrowne** [expo/turtle#81]
![image](https://user-images.githubusercontent.com/1291776/59115326-0c973500-8917-11e9-8303-aceb5875e276.png)

During setup, this fails.

**Comment by sjchmiela** [comment]
Hey @mackbrowne, thanks for submitting the issue! Could you try using `turtle-cli` from commit `d3d1919b296d9a2accef83b9a36d79a858930314` and see if the issue is solved?

**Comment by mackbrowne** [comment]
@sjchmiela how do i npm install that version using yarn?

`yarn add expo/turtle#d3d1919b296d9a2accef83b9a36d79a858930314` ??

**Comment by sjchmiela** [comment]
According to https://yarnpkg.com/lang/en/docs/cli/add/ this would certainly work:

```
yarn add https://github.com/expo/turtle.git#d3d1919b296d9a2accef83b9a36d79a858930314
```

**Comment by dsokal** [comment]
This should be fixed in the next version of `turtle-cli` which we'll publish today. Sorry for any inconvenience.

**Comment by mackbrowne** [comment]
Thanks @dsokal !
